ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/DragAndDropFile.java, ui-tests/src/test/resources/features/integrations/integration-import-export.feature
//test: `@integration-import-export`
=> [ui][fix] fix import-export tests

ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@integrations-odata-read-update`
=> reproducers for gh-5533 and gh-5386

ui-tests/src/test/resources/features/integrations/db-to-db.feature
=> Add test for inserting multiple rows provided by #5158

ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature, utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
//test: `@integrations-ftp-to-ftp`
=> [ui][fix] Fix ftp-to-ftp test

rest-tests/src/test/resources/features/soak-deployment.feature, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java, ui-tests/src/test/resources/features/integrations/google-sheets.feature
also fixes rest soak test test
//test: `@google-sheets`
=> google-sheets fix tests to work with react ui

template/prod.template.yml, utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
* increased timeout for restarting integration (Published -> Pending)
//skip-ci
=> Add oauth 4.0.0 to the template for PublicApi tests

ui-tests/src/test/resources/features/integrations/data-buckets.feature
//test: `@integrations-data-buckets`
=> [ui][fix] fix dropbox creation in data buckets

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
=> [ui][stabilize] add wait to stabilize form filling

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@oauth-validate-connectors`
=> [ui][stabilize] stabilize OAuth connection validation test

pom.xml, rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java, rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature, rest-tests/src/test/resources/features/upgrade-syndesis.feature, ui-tests/pom.xml, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
=> [FUSEQE-5032] Re-enable upgrade tests + refactor

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
//test: `@apicurio-check-operations-change-add`
=> [ui][fix] fix api client connector root selector

ui-tests/src/test/resources/features/integrations/google-sheets.feature
=> google-sheets: fix create spreadsheet

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/resources/features/customizations/connectors/webhook.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/google-sheets.feature, ui-tests/src/test/resources/features/integrations/kudu.feature, ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature, ui-tests/src/test/resources/features/integrations/webhook-db.feature, ui-tests/src/test/resources/features/other/integration-activity.feature, ui-tests/src/test/resources/features/other/integration-metrics.feature
=> [ui][stabilize] stabilize webhook JSON specification

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/datashapes.feature
//test: `@integrations-datashapes`
=> [ui][new] test integration input datashape refresh

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [ui][fix] fix salesforce OAuth validation

template/prod.template.yml
=> [Template] Sync with fuse-online-install

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> Make sure nexus is used

ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
//test: `@webhook-api-connector-list-tasks`
=> [fix][ui] webhook-api-connector-list-tasks

rest-tests/src/test/resources/features/upgrade-prod.feature, rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
=> [Upgrade] Prod upgrade changes

ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature
//test: `@integrations-conditional-flows-add-delete-step or @delete-tag`
=> [ui][stabilize] stabilize conditional flow and cicd features

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
//test: `@integrations-amq-to-rest-xml-message`
=> Make _really_ sure nexus is used

ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/resources/features/integrations/api-provider.feature
//test: `@api-provider-conditional-flow or @conditional-flow`
=> Added test for API Provider with conditional flow

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [UI][fix] - logout page on OCP4

pom.xml, rest-tests/pom.xml
=> [FUSEQE-5318] Add dependency on syndesis-cli for upgrade tests

utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java, utilities/src/main/java/io/syndesis/qe/utils/ODataUtils.java, utilities/src/main/resources/templates/syndesis-wildfly.yml
=> New odata svc changes

README.md, template/prod.template.yml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [FUSEQE-4983] Add private registries handling

utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
=> Fix datamapper id

ui-tests/src/test/java/io/syndesis/qe/pages/login/RHDevLogin.java, ui-tests/src/test/resources/features/quickstarts/db-to-db.feature, ui-tests/src/test/resources/features/quickstarts/hello-world.feature, utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
//test: `@rest and @publicapi`
=> [fix] - fixed login page on staging and changed clean up in PublicOauth

ui-tests/src/test/java/io/syndesis/qe/pages/connections/Connections.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/SelectConnectionType.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseConnection.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java, ui-tests/src/test/resources/features/other/integration-activity.feature, ui-tests/src/test/resources/features/other/integration-metrics.feature
* Activity and Metrics tests were updated according to fixed issues
* Checkstyle correction in the updated classes
//test: `@activity`
=> [UI][fix] - Fixed selector for choosing connection or step

rest-tests/src/test/resources/features/publicapi/environments.feature, rest-tests/src/test/resources/features/publicapi/integrations.feature, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdDialogSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java, ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature, ui-tests/src/test/resources/features/other/publicapi/export-import.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
//test: `@rest and (@publicapi and (not @gh-6360))`
=> [rest][improvement] - decreased time (on half) of execution @PublicApi

ui-tests/src/test/java/io/syndesis/qe/steps/other/ODataSteps.java, ui-tests/src/test/resources/features/integrations/odata.feature, utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
//test: `@integrations-odata-read-update`
=> reproducers for gh-5060 and gh-5241

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/Connections.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java, ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
=> Reworked forms to pf4

ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature
=> [UI] - Added test for a number of tag usages

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/database/PeriodicSql.java
=> [UI][fix] Changed dropdown-menu to pf-c-dropdown__menu

rest-tests/src/test/resources/features/upgrade-prod.feature, rest-tests/src/test/resources/features/upgrade-syndesis.feature
=> [Upgrade] Remove workarounds for schema change

ui-tests/src/test/resources/features/integrations/concur.feature, ui-tests/src/test/resources/features/integrations/data-buckets.feature, ui-tests/src/test/resources/features/integrations/gmail.feature, ui-tests/src/test/resources/features/integrations/google-calendar.feature, ui-tests/src/test/resources/features/integrations/google-sheets.feature, ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature, ui-tests/src/test/resources/features/integrations/template.feature, ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature, ui-tests/src/test/resources/features/integrations/twitter-to-db.feature, ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature, ui-tests/src/test/resources/features/other/settings-oauth.feature, ui-tests/src/test/resources/features/other/support-page.feature
=> [OAuth] Add tags for oauth tests

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java, ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java, ui-tests/src/test/resources/features/integrations/api-provider.feature
Reproducers for 
https://github.com/syndesisio/syndesis/issues/4031
https://github.com/syndesisio/syndesis/issues/6230
//test: `@gh-4031 or  @gh-6230`
=> [UI] - reporducer for gh-4031 and gh-6230

rest-tests/src/test/resources/features/integration-box.feature, utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java, utilities/src/main/java/io/syndesis/qe/bdd/entities/SeparatorType.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java
//test: `@integration-box-amq`
=> [FUSEQE-5676] Add reproducer for mapping box download response

ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/resources/features/connections/oauth.feature
//test: `@conditional-flow or @oauth`
=> Fixed Conditional flow selectors

README.md
=> delete date from readme as it is tracked by github file changes

utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
=> [FUSEQE-5921] Move box folder id to credentials

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/TemplateSteps.java, ui-tests/src/test/resources/features/integrations/template.feature, ui-tests/src/test/resources/templates/code_editor_test.txt
=> [ui][fix] Changed template to work on React UI 

ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
=> [FUSEQE-5956] Fix twitter to salesforce basic scenario

rest-tests/src/test/resources/features/publicapi/integrations.feature, ui-tests/src/test/resources/features/other/integration-metrics.feature, ui-tests/src/test/resources/features/other/publicapi/cicddialog.feature, ui-tests/src/test/resources/features/other/publicapi/export-import.feature
=> Migrate open GH issues to ENTESB anotation

README.md
=> [readme-correction] Small correction to make text more clear

utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
=> [fix] adapted latest changes in ContinuousDeliveryEnvironment

rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
needs https://github.com/syndesisio/syndesis-qe/pull/1080
=> [FUSEQE-5902] Fix rest rests

ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@gh-5151 or @gh-5067`
=> reproducers for gh-5151 and gh-5067

ui-tests/src/test/java/io/syndesis/qe/steps/other/ODataSteps.java, ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@gh-5559 or @gh-integrations-odata-create`
=> reproducer for gh-5559

rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
=> Fix upgrade image check in operator for RHEL 7 and 8

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/CreateIntegrationSteps.java, ui-tests/src/test/resources/features/integrations/integration-status.feature
//test: `@integrations-check-starting-status`
=> Fix @integrations-check-starting-status tests

rest-tests/src/test/resources/features/integration-sf-producers.feature, rest-tests/src/test/resources/features/integration-sqs.feature, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/google-calendar.feature, ui-tests/src/test/resources/features/integrations/odata.feature, ui-tests/src/test/resources/features/integrations/sql-connector.feature
=> [FUSEQE-5597] Annotate long running features

rest-tests/src/test/resources/features/publicapi/environments.feature, rest-tests/src/test/resources/features/publicapi/integrations.feature, ui-tests/src/test/resources/features/other/publicapi/export-import.feature, utilities/src/main/java/io/syndesis/qe/publicapisteps/EnvironmentsPublicApiSteps.java, utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
//test: `@publicapi and (not (@ENTESB-11653 or @ENTESB-11386))`
=> [FUSEQE-5828] - Update Public API tests

rest-tests/src/test/resources/features/integration-kafka.feature, rest-tests/src/test/resources/features/integration-sf-db.feature, rest-tests/src/test/resources/features/integration-sf-producers.feature, rest-tests/src/test/resources/features/integration-tw-sf.feature, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/resources/features/integrations/integration-import-export.feature, ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature, ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
//test: `@integrations-twitter-to-salesforce or @integrations-salesforce-to-db or @integration-kafka or @integration-sf-db or @integration-sf-producers or @integration-tw-sf`
=> [FUSEQE-5830] - updated salesforce UI tests

rest-tests/src/test/resources/features/publicapi/environments.feature, rest-tests/src/test/resources/features/publicapi/integrations.feature, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdDialogSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
//skip-ci
A backport of this PR https://github.com/syndesisio/syndesis-qe/pull/1053
=> [rest][1.7.x] - PublicOauth template fixes

rest-tests/src/test/resources/features/publicapi/integrations.feature, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
//skip-ci
Skip CI due to ENTESB-11388
(HotFix) I added missing tag to the PublicApi test. (I forget about it in this PR https://github.com/syndesisio/syndesis-qe/pull/1092 because the test was skipped due to ENTESB-11653)
=> [FUSEQE-6013] - updated Metrics tab selectors

ui-tests/src/test/resources/features/connections/connections.feature, ui-tests/src/test/resources/features/connections/oauth.feature, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature, ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature, ui-tests/src/test/resources/features/integrations/concur.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/data-buckets.feature, ui-tests/src/test/resources/features/integrations/datashapes.feature, ui-tests/src/test/resources/features/integrations/gmail.feature, ui-tests/src/test/resources/features/integrations/integration-import-export.feature, ui-tests/src/test/resources/features/integrations/kudu.feature, ui-tests/src/test/resources/features/integrations/log-connector.feature, ui-tests/src/test/resources/features/integrations/mqtt.feature, ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature, ui-tests/src/test/resources/features/integrations/telegram.feature, ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature, ui-tests/src/test/resources/features/other/3scale.feature, ui-tests/src/test/resources/features/other/login-logout.feature, ui-tests/src/test/resources/features/other/settings-oauth.feature, ui-tests/src/test/resources/features/other/support-page.feature
=> [ui] update maintainers of features

utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
Old ftp server was slow, so new one is to be deployed.
//test: `@ftp`
=> [FUSEQE-5979] Part 1, new ftp server

utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
=> [1.7.x] -  Fix namespace for service account 

utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
//test: `@publicapi and @rest`
=> [REST] - Fix namespace for service account

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
=> [UI] Create screenshot even if the test fails in background

utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
=> [Server] Print useful info when something went wrong with the server

ui-tests/src/test/resources/features/integrations/service-now.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java, utilities/src/main/java/io/syndesis/qe/servicenow/model/Incident.java
=> fix service-now tests

README.md, pom.xml, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java, utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java, utilities/src/main/java/io/syndesis/qe/issue/IssueState.java, utilities/src/main/java/io/syndesis/qe/issue/SimpleIssue.java, utilities/src/main/java/io/syndesis/qe/utils/IssueHooksUtils.java
=> [FUSEQE-5863] Add Jira issue hooks

rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature, rest-tests/src/test/resources/features/upgrade-syndesis.feature
=> [FUSEQE-6153] Temporary disable upgrade tests

README.md, rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/resources/syndesis-minimal.yaml
Partial implementation of FUSEQE-6043 (only the operator deployment implemented, still needs a way to specify the CR)
//test: `@smoke`
=> [FUSEQE-6043] Deploy operator from generated resources

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [FUSEQE-6043] Fix for latest operator tag

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [FUSEQE-6043] Further fix for new install

ui-tests/src/test/resources/features/integrations/db-to-db.feature
=> [FUSEQE-6030] Fix flaky smoke test

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/ConditionalFlows.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/steps/ConditionalFlowsSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/resources/features/integrations/conditional-flow.feature
//test: `@integrations-conditional-flows`
=> Fix Conditional flow tests

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/resources/syndesis-minimal.yaml
=> Tweak minimal CR

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/resources/features/integrations/google-sheets.feature
=> fix: google sheet stale elements fix

ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderFlowSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/swagger/connectors/todo.json
=> Happy path API Provider error handling

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
To fill form added part with dropdown 
//test: `@integrations-ftp-to-ftp`
=> [FUSEQE-5979] Part 2, update form fill with dropdown

utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
//test: `@integrations-ftp-to-ftp`
Can only be tested once our test suite works with 1.8, as the issue is not fixed in 1.7
=> Remove gh-6141 workaround

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java, rest-tests/src/test/resources/features/integration-box.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
=> [FUSEQE-5666] Add test for box download datamapper

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [Deploy] Use syndesis url as route if set

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> Fix installation with prod operator

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> Added enum entry for AWS DDB

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [Operator] Fix operator name / tag parsing

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
=> [FUSEQE-6268] - Fixed Metrics scenario

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> Use correct version for 1.7.x

rest-tests/src/test/resources/features/integration-box.feature
=> [FUSEQE-5666] Assure that the poll will happen only once at start

ui-tests/src/test/resources/features/integrations/import-edit.feature
=> Annotated the SQL dropdown issue

ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
//test: `@dropbox-integration`
=> [ui] Set value of dropbox upload mode

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/utils/IssueHooksUtils.java
=> [Jira hook] Fix jira hook name

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> Use new syndesis operator binary

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> Remove patchImageStreams and importProdImages

ui-tests/src/test/resources/features/integrations/api-provider.feature
=> [typo] Fix typo in ENTESB

ui-tests/src/test/resources/features/integrations/webhook-db.feature
=> [FUSEQE-5449] Batch Update automated test for DB

ui-tests/src/test/resources/features/integrations/import-edit.feature
=> Add ENTESB annotation to the import-edit scenario

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
//test: `@apicurio-customization and not @disabled`
=> [FUSEQE-6035] Reparation of apicurio tests

rest-tests/src/test/resources/features/integration-sns.feature, rest-tests/src/test/resources/features/integration-sqs.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/SQSValidationSteps.java
=> [SQS-SNS] Purge only relevant queues for each test

ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
//test: `@twitter-direct-messages-send`
=> [FUSEQE-6286] Fix twitter direct message send

ui-tests/src/test/resources/features/connections/oauth.feature, ui-tests/src/test/resources/features/other/settings-oauth.feature, ui-tests/src/test/resources/features/other/support-page.feature
//test: `@oauth-gcalendar or @oauth-salesforce`
=> Oauth text fix - google calendar

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [ui] do not login if already logged in hack

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/slack/ReadMessages.java, ui-tests/src/test/resources/features/integrations/slack.feature
//test: `@slack and not(@disabled)`
=> [FUSEQE-6269] Fixed Slack scenarios

rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java, rest-tests/src/test/resources/features/integration-lifecycle.feature
//test: `@integrations-lifecycle`
=> [integration-lifecycle] Allow the integration lifecycle tests

pom.xml, ui-tests/src/test/resources/features/integrations/dynamodb.feature, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/DynamoDbValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/DynamoDbUtils.java
//test: `@dynamodb`
One of the tests should fail because (@dynamodb-query) because of [ENTESB-11767](https://issues.jboss.org/browse/ENTESB-11767)
=> [FUSEQE-5668] Add dynamoDb basic test set

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature, ui-tests/src/test/resources/features/other/support-page.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
//test: `@support-page-download-specific-diagnostic or @integrations-twitter-to-salesforce`
=> [tw_sf] Fix - dropdown was reintroduced

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [UI] Quick fix login page

README.md, ui-tests/pom.xml
=> [UI] Download drivers only with download-drivers profile

ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
Updated this test, so it will work also with the second set of credentials
=> [tw_sf] Fix for second set of credentials

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [ui] Google choose account workaround

rest-tests/src/test/resources/features/integration-sqs.feature
//test: `@integration-sqs-sqs-max-objects`
=> [SQS] Add missing queues to purge

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/resources/features/other/3scale.feature, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> Syndesis API discovery by 3scale fix

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@integrations-odata-create`
=> Add sleep in order to let data mapper fully load

ui-tests/src/test/resources/features/integrations/db-to-db.feature
=> [DB-to-DB] Fix smoke test - remove unnecessary open collection mapping

pom.xml, ui-tests/src/test/java/io/syndesis/qe/steps/other/JiraSteps.java, ui-tests/src/test/resources/features/integrations/jira.feature, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/utils/jira/JiraClientFactory.java, utilities/src/main/java/io/syndesis/qe/utils/jira/JiraOAuthGetAccessToken.java, utilities/src/main/java/io/syndesis/qe/utils/jira/OAuthJiraAuthenticationHandler.java
This is a semi-automated testing of jira connector.
Can't be run automatically for now, need to setup a jira instance for the integration, hence should be run manually.
=> [FUSEQE-5665] semi-automated testing of jira connector

ui-tests/src/test/resources/features/integrations/kudu.feature
//test: `@integrations-kudu-insert`
=> [FIX] Kudu test fix test

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> commit to personal test branch

ui-tests/src/test/resources/features/integrations/google-sheets.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleSheetsValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java
//test: `@google-sheets`
expect to fail 2 tests .. one is disabled
=> google-sheets: fix tests to work with updated component

ui-tests/src/test/java/io/syndesis/qe/steps/other/ServiceNowSteps.java, ui-tests/src/test/resources/features/integrations/service-now.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
=> service-now: add posibility to run tests in parallel on different browsers

ui-tests/src/test/resources/features/integrations/sql-connector.feature
//test: `@sql-connector-predicates`
=> Add ENTESB-11487 annotation and consolidate test

rest-tests/src/test/resources/features/integration-edit-dc.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
//test: `@integration-edit-dc`
=> [ENTESB-11690] Add reproducer for ENTESB-11690, ENTESB-11640, ENTESB-10194

ui-tests/src/test/resources/features/other/login-logout.feature
//test: `@logout-test-logout or @logout-test-logout-login`
=> [FIX] Login logout test fix

utilities/src/main/resources/templates/syndesis-amq.yml
//test: `@integrations-amq-to-rest`
=> [AMQ] Use label for syndesis-amq to be selectable by broker-amq-tcp svc

ui-tests/src/test/resources/features/integrations/integration-import-export.feature, ui-tests/src/test/resources/features/integrations/slack.feature, ui-tests/src/test/resources/features/other/integration-activity.feature
//test: `@slack-check-message-data-mapper and @integration-import-export-classic-input`
=> [FUSEQE-6350][fix] - Fix period time for Slack scenarios

ui-tests/src/test/resources/features/integrations/odata.feature, utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
Refactor WildFlyTemplate cleanUp method
//skip-ci
=> Delete one odata scenario - no longer needed

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java
=> fix Name fill before publishing an integration

ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java, ui-tests/src/test/resources/features/integrations/google-sheets.feature
also refactor scenario about copying big spreadsheet
//test: `@google-sheets`
=> google-sheets: fix pivot table test on firefox

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
//test: `@ftp-download-ftp-upload`
=> [FIX] FTP to FTP test fix

ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/swagger/connectors/todo.json
=> [ui] fixed some failing api provider issues

ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@integrations-odata-create`
=> Fix integrations-odata-create - open data mapper collections

ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
//test: `@apicurio-check-security-settings-oauth-2`
=> [FUSEQE-6035] Apicurio test preliminar fix

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, rest-tests/src/test/resources/features/upgrade-prod.feature
=> [FUSEQE-6153] Add checks for upgraded stuff

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [UI] Fix login for 4.2

ui-tests/src/test/resources/features/integrations/datashapes.feature
//test: `@integrations-datashapes-input-change-conditional-flow`
=> Fix @integrations-datashapes-input-change-conditional-flow

ui-tests/src/test/resources/features/integrations/db-to-db.feature
//test: `@db-insert-multiple-rows`
=> [ui][fix] fix @db-insert-multiple-rows test

utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
=> [ResetDB] Cleanup openshift resources

ui-tests/src/test/resources/features/connections/oauth.feature
=> disable oauth calendar test

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
//test: `@integration-edit-dc or @3scale`
=> [Utils] Harden waiting for next pod

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
if there is a problem with the route, it ends with:
```
java.lang.AssertionError: Syndesis route failed to provision because of: a route in another namespace holds avano-syndesis.my-minishift.syndesis.io and is older than syndesis
```
//skip-ci
=> [Install] Add a check for route condition

pom.xml
=> [MQTT] Bump mqtt client version

README.md
=> GH token description added to most common problems

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [ui] Fix login to OCP 4 on OpenStack

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java, ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
//test: `@api-provider-prevent-publishing-empty-integration-by-deleting-all`
=> [FIX] Apicurito step fix

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
=> [Deploy] Print the exception when the test fails in beforeclass

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> [TestConfiguration] Catch exception in test configuration constructor

pom.xml, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/MongoDBSteps.java, ui-tests/src/test/resources/features/integrations/mongodb.feature, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/MongoDb36Template.java
=> [ui] Add MongoDB happy path tests

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, utilities/src/main/resources/kafka/kafka-ephemeral.yaml, utilities/src/main/resources/kafka/strimzi-deployment.yaml
=> [Kafka] Bump amq-streams to 1.3.0

ui-tests/src/test/resources/features/integrations/mongodb.feature
//test: `@mongodb-update`
Didn't really have any effect, fixing just for consistency
=> [ui] Fix typo in mongo tests

utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
=> Fix public oauth image version

utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java, utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java, utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
=> [Logging] Add error logging to the cases where exception is raised

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/Editor.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature, ui-tests/src/test/resources/features/other/integration-info.feature
//test: `@apicurio-check-security-settings-api-key or @ENTESB-11685`
=> [UI] - Updated existing test as reproducer for ENTESB-11474

ui-tests/src/test/resources/features/integrations/data-mapper.feature
=> Add reproducer for ENTESB-11870

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> Fixed logout test on remote OCP4.2

rest-tests/src/test/resources/features/irc.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/IrcValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/IrcTemplate.java, utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
=> [IRC] Rework interacting with irc server

rest-tests/src/test/resources/features/integration-sns.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/SNSValidationSteps.java
=> [SNS] Refactor SNS from DB to AMQ

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
=> [Kafka] Fix kafka cleanup

pom.xml, rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/AbstractStep.java, utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java, utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java, utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsEndpoint.java
Updates according to changes in master:
- Json was moved and renamed to JsonUtils
- Last processed returns Instant
=> Bump Syndesis version to 1.9

ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
=> [UI] - fix apicurio tests

ui-tests/src/test/resources/features/integrations/api-client-connector.feature, ui-tests/src/test/resources/features/integrations/data-buckets.feature, ui-tests/src/test/resources/features/integrations/db-to-db.feature, ui-tests/src/test/resources/features/integrations/email.feature, ui-tests/src/test/resources/features/integrations/gmail.feature, ui-tests/src/test/resources/features/integrations/import-edit.feature, ui-tests/src/test/resources/features/integrations/jira.feature, ui-tests/src/test/resources/features/integrations/log-connector.feature, ui-tests/src/test/resources/features/integrations/slack.feature, ui-tests/src/test/resources/features/integrations/telegram.feature, ui-tests/src/test/resources/features/integrations/template.feature, ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature, ui-tests/src/test/resources/features/quickstarts/db-to-db.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
=> Updated tests with Contact table

rest-tests/src/test/resources/features/publicapi/integrations.feature, ui-tests/src/test/resources/features/other/integration-metrics.feature, utilities/src/main/java/io/syndesis/qe/publicapisteps/EnvironmentsPublicApiSteps.java
//test: `@export-import or @metrics-error`
=> Fixed small issues with PublicApi tests

utilities/src/main/java/io/syndesis/qe/utils/SQSUtils.java
=> [SQS] Retry purge queue after delay if there is some already in progress

ui-tests/src/test/resources/features/integrations/google-sheets.feature
`@add-chart-basic-chart-to-spreadsheet`
=> google-sheets: add basic chart test

ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
=> [ui] stabilized api provider tests on OCP4

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/resources/syndesis-minimal.yaml
=> Test support

ui-tests/src/test/resources/features/integrations/api-provider.feature
=> [ui] api-provider modification still had some integrations running

ui-tests/src/test/resources/features/connections/connections.feature
=> validate credentials from @smoke removed

ui-tests/src/test/resources/features/integrations/telegram.feature
=> fix in telegram test

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> [SnoopSelectors] Rename property for snoopselectors

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [Deploy] Add info about cluster and namespace

utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
=> [FUSEQE-7042][FIX] - wait till integrations are deleted

ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java, ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
=> Smoke fix for Chrome

rest-tests/src/test/resources/features/integration-lifecycle.feature, rest-tests/src/test/resources/features/integration-sns.feature, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/concur.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/data-buckets.feature, ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature, ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature, ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature, ui-tests/src/test/resources/features/integrations/db-to-db.feature, ui-tests/src/test/resources/features/integrations/email.feature, ui-tests/src/test/resources/features/integrations/google-sheets.feature, ui-tests/src/test/resources/features/integrations/integration-import-export.feature, ui-tests/src/test/resources/features/integrations/integration-status.feature, ui-tests/src/test/resources/features/integrations/kudu.feature, ui-tests/src/test/resources/features/integrations/log-connector.feature, ui-tests/src/test/resources/features/integrations/odata.feature, ui-tests/src/test/resources/features/integrations/sql-connector.feature, ui-tests/src/test/resources/features/integrations/template.feature, ui-tests/src/test/resources/features/other/integration-activity.feature, ui-tests/src/test/resources/features/other/integration-metrics.feature
=> [FUSEQE-7043] - updated duplicate integration names

utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java, utilities/src/main/resources/templates/syndesis-default-amq-service.yml
//test: `@integrations-amq-to-rest`
=> [FUSEQE-7046] Fix Amq to rest scenario

ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/detail/ConnectionDetail.java
=> [FUSEQE-7042] - Fix smoke test

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/IntermediateSteps.java, rest-tests/src/test/resources/features/soak-deployment.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
//skip-ci
add reset services before scenario start
=> [soak-test] fix delay problem

rest-tests/src/test/resources/features/timer-connector.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
=> [rest-timer] fix assert

rest-tests/src/test/resources/features/soak-deployment.feature, rest-tests/src/test/resources/features/timer-connector.feature, ui-tests/src/test/resources/features/integrations/google-sheets.feature, ui-tests/src/test/resources/features/integrations/service-now.feature, ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
=> [Maintainer] Remove mmelko from maintainers

ui-tests/src/test/resources/features/integrations/odata.feature
=> [FUSEQE-5685] Add reproducer for gh-5067

ui-tests/src/test/resources/features/other/support-page.feature
//test: `@support-page-version-check`
=> [FIX] Fix support page version test

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [Route] Bring back route in CR

ui-tests/src/test/java/io/syndesis/qe/reports/selectors/ReportUtils.java, ui-tests/src/test/java/io/syndesis/qe/reports/selectors/SelectorUsageReporter.java, ui-tests/src/test/resources/templates/data_test_id_template.vm
=> [selector-reports] Tweaked test-id rewrite test output

ui-tests/src/test/resources/features/integrations/odata.feature
=> [FUSEQE-5684] Add reproducer for gh-5151

ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@integrations-odata-read`
=> [odata-test-fix] Remove $ from scenario name

ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java, ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
//test: `@data-buckets-usage-2`
=> [FIX] Fix databucket usage test

README.md, pom.xml, rest-tests/pom.xml, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/MqttValidationSteps.java, utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/java/io/syndesis/qe/utils/FtpClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/JmsClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
//skip-ci
* Changed test suite to use two users
Also removed namespace lock that imho wasn't used by anyone
* Refactored README - removed trailing whitespaces, adding new stuff, removing old stuff
* Make the repo buildable without any special repo by default
=> [FUSEQE-7078] Use two users for installing and using Syndesis

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/resources/syndesis-minimal.yaml
=> Server features fix

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
//test: `@mqtt-connection-publish-subscribe-request`
=> [FIX] Fix mqtt test

ui-tests/src/test/resources/features/connections/oauth.feature
=> [FIX] Fix oauth tests

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/Editor.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/Alert.java, ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java, ui-tests/src/test/resources/features/other/settings-oauth.feature
//test: `@settings-oauth-validate`
=> [FUSEQE-6793] Remove all alerts before alert check

ui-tests/src/test/resources/features/other/support-page.feature
//test: `@support-page-download-specific-diagnostic`
=> [FUSEQE-6028] Remove external services from support page

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
//test: `@activity-test`
small correction in code. element from method argument was not used
=> [FIX] Fix page object

ui-tests/src/test/resources/features/integrations/odata.feature
=> [odata-fix] Fix odata tests - changed data-testid

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java, rest-tests/src/test/resources/features/integration-box.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/AccountUtils.java
=> [ENTESB-11433] Add reproducers for ENTESB-11433

README.md, rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/AboutPageSteps.java, utilities/src/main/java/io/syndesis/qe/Image.java, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
=> [FUSEQE-7639] Use properties file for image

ui-tests/src/test/java/io/syndesis/qe/steps/other/MongoDBSteps.java, ui-tests/src/test/resources/features/integrations/mongodb.feature, utilities/src/main/java/io/syndesis/qe/templates/MongoDb36Template.java
//test: `@integrations-mongodb`
=> [FUSEQE-7062] Update mongodb tests and extend them about checking new functionalities

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [FUSEQE-7639] Retry updating operator dc env vars

rest-tests/src/test/resources/features/operator-deployment.feature, utilities/src/main/java/io/syndesis/qe/Image.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/java/io/syndesis/qe/resource/impl/DV.java
=> Prod operator Camel-K, DV

rest-tests/src/test/resources/features/integration-lifecycle.feature
//test: `@integrations-lifecycle`
=> [fix-lifecycle] Fix integration lifecycle tests

ui-tests/src/test/resources/features/integrations/dynamodb.feature
=> [AWS-DDB] Fix failing aws-ddb tests

rest-tests/src/test/resources/features/timer-connector.feature
=> [timer] Fix timer connector tests

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java, ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java, ui-tests/src/test/resources/features/integrations/api-provider.feature
=> [refactor] API Provider request steps

pom.xml, ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java, ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java, ui-tests/src/test/java/io/syndesis/qe/hooks/SelectorSnooper.java, ui-tests/src/test/java/io/syndesis/qe/pages/MainPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/Todo.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewActions.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewEditConnectorDetails.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/BasicFilter.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/login/GitHubLogin.java, ui-tests/src/test/java/io/syndesis/qe/pages/login/MinishiftLogin.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
=> [update-selenide] Update selenide in order to be able to use chrome 79

rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
//test: `@integrations-lifecycle-try-with-same-name`
=> [REST-fix] - Fixed lifecycle-try-with-same-name test

pom.xml, ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java, ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java, ui-tests/src/test/java/io/syndesis/qe/hooks/SelectorSnooper.java, ui-tests/src/test/java/io/syndesis/qe/pages/MainPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/Todo.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewActions.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewEditConnectorDetails.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/BasicFilter.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/login/GitHubLogin.java, ui-tests/src/test/java/io/syndesis/qe/pages/login/MinishiftLogin.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
=> [selenide-update] Update selenide version in order to use chrome v.79

utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
=> [Formatter] Add newline to each line

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> [default-version] Set default version of syndesis and operator

ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
=> [fix] salesforce dropdown id fix

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
=> [FUSEQE-7714] fixed login on OCP4.3

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-7775] Handle multiple versions of CRDs

utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
=> [OCP4.2] - workaround for lost connection (due to exception)

ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/detail/DetailSteps.java
=> Fix api connector - validate connector detail

ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java
//test: `@integrations-conditional-flows-add-delete-step or @integrations-conditional-flows-add-update-step`
=> Fix conditional flows - dataTestId of Conditional flow container element

ui-tests/src/test/resources/features/integrations/service-now.feature
//test: `@integrations-servicenow-1`
=> [servicenow] Fix get incident from service now

utilities/src/main/java/io/syndesis/qe/bdd/validation/DropBoxValidationSteps.java
=> [Dropbox] Catch exception when deleting file that is not present

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/features/publicapi/integrations.feature, rest-tests/src/test/resources/operator/spec/backup.yml, ui-tests/src/test/resources/features/other/publicapi/export-import.feature, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java, utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java, utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java, utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
//skip-ci as our automation still runs against an old version (1.9.100-20191210)
=> [ENTESB-12114] Add backup and restore test

rest-tests/src/test/resources/features/integration-box.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
=> [Fix] Fix FTP step + add longer delay for box test

ui-tests/src/test/resources/features/integrations/slack.feature
=> [FUSEQE-7057] Fix Slack scenario

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@validate-connection-credentials`
=> [fix] Added enum entry for SFTP credentials

utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [FUSEQE-7810] Fix deployment when more versions of CRD are present

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [CRD] Another fix for existing CRD but in different version

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
=> [CRD] Fix for different count of versions

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
//test: `@activity-test or @metrics-test`
=> [FUSEQE-6925]-Sync time with OCP

pom.xml, utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
=> [Atlasmap] Bump atlasmap version

ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
=> [fix] Apicurio tests quick fix

ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/SftpValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/SFTP.java, utilities/src/main/java/io/syndesis/qe/utils/SftpUtils.java
//test: `@integrations-sftp-to-sftp`
=> [SFTP-FIX-4.3] Fix SFTP on ocp 4-3

utilities/src/main/java/io/syndesis/qe/resource/impl/MySQL.java
//test: `@integrations-db-to-db-mysql`
=> [FIX] Relocate mysql image to our own repository

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/spec/backup.yml, rest-tests/src/test/resources/operator/spec/components/database/externalDb.yml, rest-tests/src/test/resources/operator/spec/components/server/integrationLimit.yml
=> [Operator] Use nexus for tests with integration

ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature, ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/SftpValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/FTP.java, utilities/src/main/java/io/syndesis/qe/utils/FtpClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java, utilities/src/main/java/io/syndesis/qe/utils/SftpClientManager.java
//test: `@integrations-ftp-to-ftp`
=> [FUSEQE-7785] Fixing FTP server, timeout

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java, ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature
=> [FUSEQE-6253] Added api-key tests for api client

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java, ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature, ui-tests/src/test/resources/features/integrations/db-to-db.feature, ui-tests/src/test/resources/features/integrations/integration-status.feature, ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
//test: `@integration-check-starting-status-on-home-page or @DB-custom-api-connector-integration`
=> [fix] fixed typo in integration names

ui-tests/src/test/resources/features/integrations/dynamodb.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/DynamoDbValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/DynamoDbUtils.java
=> [Dynamo-DB] Add update test for Dynamo DB - ENTESB-11740

pom.xml, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java, utilities/src/main/java/io/syndesis/qe/resource/impl/HTTPEndpoints.java, utilities/src/main/java/io/syndesis/qe/resource/impl/WildFlyS2i.java, utilities/src/main/resources/templates/syndesis-wildfly.yml
//test: `@integration-http-consumer-get or @integration-amq-irc or @simple-timer or @integrations-odata-read`
=> [FUSEQE-7546] Remove OCP4HACKs

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
=> [Deploy] Add lastUsedBy annotation to the project

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [Config] Parse openshift route suffix from api if not set

pom.xml, rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java, utilities/src/main/resources/templates/syndesis-amq.yml
=> [Fixes] Small fixes

README.md
=> [FUSEQE-8010] Update readme to reflect new test.properties options

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/CiCd/ManageCiCdPageSteps.java, ui-tests/src/test/resources/features/other/publicapi/export-import.feature, utilities/src/main/java/io/syndesis/qe/Addon.java, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
* Update Public API test
* Add logic how to enable/disable addons
* Extract function for executing operator
//test: `@publicapi`
=> [FUSEQE-7676] - Update Public API tests

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java, ui-tests/src/test/resources/features/other/integration-metrics.feature, utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
=> [FUSEQE-8013] Fix issue when the time is same

utilities/src/main/java/io/syndesis/qe/resource/impl/Kudu.java
=> [FIX] Kudu server for OCP 3.11 fix

pom.xml, rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/manual_restore.sh, rest-tests/src/test/resources/operator/spec/backup-external-db.yml, rest-tests/src/test/resources/operator/spec/backup-multiple.yml, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
=> [ENTESB-12645] Add backup & restore with external db

rest-tests/src/test/resources/features/irc.feature
=> [ENTESB-9985] Add ENTESB-9985 reproducer

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java, ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/openapi.feature, ui-tests/src/test/resources/openapi/connectors/todo.json, ui-tests/src/test/resources/openapi/connectors/todo.yaml
=> [FUSEQE-6965] Added tests for OpenAPI 3.x support

ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/customizations/connectors/invalid-swagger.feature, ui-tests/src/test/resources/features/customizations/connectors/webhook.feature, ui-tests/src/test/resources/features/customizations/extension-CRUD.feature, ui-tests/src/test/resources/features/integrations/api-client-connector.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/datashapes.feature, ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature, ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature, ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature, ui-tests/src/test/resources/features/integrations/db-to-db.feature, ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature, ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature, ui-tests/src/test/resources/features/integrations/import-edit.feature, ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature, ui-tests/src/test/resources/features/integrations/integration-status.feature, ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature, ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature, ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
=> [UI] Update test maintainers

ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
//test: `@settings-oauth-validate`
=> [FUSEQE-8120] Fix stale element exception, increase test stability

ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature, ui-tests/src/test/resources/features/integrations/openapi.feature
=> [UI] Add missing maintainers

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/KafkaSteps.java, ui-tests/src/test/resources/features/integrations/db-to-kafka.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/Kafka.java
=> [FUSEQE-7781] Autodiscovery AMQ streams test

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/resources/features/other/camelk.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [camel-k] Added test for disabled API client

ui-tests/src/test/resources/features/other/camelk.feature
=> [fix] Added description to scenario

utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java, utilities/src/main/java/io/syndesis/qe/issue/SimpleIssue.java
//test: `@api-provider-delete`
=> [FUSEQE-6148] added list of all issues that affected the test run

ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/Todo.java, ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/resources/templates/syndesis-amq.yml, utilities/src/main/resources/templates/syndesis-default-amq-service.yml
//test: `@integrations-amq-to-rest or @integrations-amqp-to-amqp`
=> [FUSEQE-8265] - Update service for AMQ broker

utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
=> [Report] Remove <li> elements from the report

ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
//test: `@integrations-db-to-kafka-to-db`
=> [FIX] Fix amq auto detecting

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/PreviousSyndesis.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-8269] Use regular user for manipulating the CR

rest-tests/src/test/resources/features/operator-deployment.feature
=> [Operator] Fix DV scenarios

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java, ui-tests/src/test/resources/features/integrations/amq-to-rest.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java
//test: `(@rest and @integration-db-amq-aggregate) or @integrations-amq-to-rest or @integrations-servicenow-1`
=> [FUSEQE-8265] Use different account for AMQ to REST test

rest-tests/src/test/resources/features/integration-monitoring.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java
//test: `@integration-db-to-db-monitoring`
=> [Monitoring] Edit test to work with Jaeger

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
//test: `@camel-k or @activity-test`
=> [fix] Change runtime in CamelK#undeploy and Jaeger deploy

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> Hotfix for Jaeger workarounds

rest-tests/src/test/resources/operator/spec/components/server/deployIntegrations.yml
=> [Operator] Add missing repository to deployIntegrations test

utilities/src/main/resources/syndesis-minimal.yaml
=> Enable Jaeger in the PR job

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
//test: `@api-provider-prevent-publishing-empty-integration-by-deleting-all`
=> [fix] add wait before checking if element exists

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java, rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/ResourceFactory.java, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/java/io/syndesis/qe/test/InfraFail.java, utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java, utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
=> Hopefully QoL changes

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
=> [Upgrade] Check CR status and don't rely on logs

utilities/src/main/java/io/syndesis/qe/utils/SftpClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/SftpUtils.java
//test: `@integrations-sftp-to-sftp`
explanation: I cannot reproduce this sftp connection instability problem on local -> OCP, so I need to utilize jenkins. 
Since it's random problem, I'll retest this several times.
=> [FUSEQE-8363] SFTP test stabilization

rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java, rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/jaeger/jaeger-service-collector.yml, rest-tests/src/test/resources/jaeger/jaeger-service-query.yml, rest-tests/src/test/resources/jaeger/jaeger.yml, rest-tests/src/test/resources/operator/spec/addons/external-jaeger.yml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java, utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-8020] - add external jaeger test

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
=> [Deploy] Print exception to debug when user doesn't have admin rights

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
//test: `@api-provider-simple-response-type`
=> [fix] don't crash on non-existing label

utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
=> [fix] used Syndesis#ensureImagePull for Camel K

ui-tests/src/test/resources/features/integrations/db-to-kafka.feature
//test: `@integrations-db-to-kafka-to-db`
=> [FIX] Fix of @integrations-db-to-kafka-to-db

utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java, utilities/src/main/java/io/syndesis/qe/resource/impl/MySQL.java, utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
//test: `@DB-custom-api-connector-DB or @integrations-amq-to-rest or @openwire or @integrations-db-to-db-mysql`
=> [FUSEQE-8632] openwire and mysql stability improvement

utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java, utilities/src/main/java/io/syndesis/qe/resource/impl/MySQL.java, utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
//skip-ci
backport for https://github.com/syndesisio/syndesis-qe/pull/1394
=> [backport-1.10.x][FUSEQE-8632] openwire and mysql stability improvement

utilities/src/main/java/io/syndesis/qe/resource/impl/AMQ.java, utilities/src/main/java/io/syndesis/qe/resource/impl/MySQL.java, utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
//skip-ci
backport for https://github.com/syndesisio/syndesis-qe/pull/1394
=> [backport-master][FUSEQE-8632] openwire and mysql stability improvement

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> [Config] Use artifacts from 1.9.x branch

utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
=> [Operator] Fix checking version for floating tags

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java, ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/ChooseAction.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/KafkaSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/Alert.java, ui-tests/src/test/resources/features/other/integration-info.feature
=> [FUSEQE-8609] Migrate tests to PF4 ui

utilities/src/main/resources/kafka/kafka-ephemeral.yaml, utilities/src/main/resources/kafka/strimzi-deployment.yaml
=> [FUSEQE-8537] Bump amq-streams to 1.4

pom.xml
=> Bump Syndesis version

utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
=> [FIX] Support https for public API

ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/AbstractUiElementsList.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java, ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java, ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/Virtualizations.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
This PR works against https://github.com/syndesisio/syndesis/pull/8253
//skip-ci
=> [pf4 migration] Changed RowList to correspond with PF4

pom.xml
=> [Datamapper] Bump datamapper version

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
Some data tests are going to be added in https://github.com/syndesisio/syndesis/pull/8282
=> [FUSEQE-8681] API Provider & API Connector UI fixes

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/spec/addons/knative.yml
=> [Operator] Add knative addon smoke test

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/OperatorMetricsEndpointSteps.java, rest-tests/src/test/resources/features/check-operator-version.feature
//test: `@check-operator-version`
=> [FUSEQE-7950] Create automated tests for ENTESB-12333

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/OperatorMetricsEndpointSteps.java, rest-tests/src/test/resources/features/check-operator-version.feature
//test: `@check-operator-version`
=> [Backport-1.10.x][FUSEQE-7950] Create automated tests for ENTESB-12333

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCiCdDialog.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
DataTestIds: https://github.com/syndesisio/syndesis/pull/8291
=> [FUSEQE-8681] pf4 migration - DataTestID for activity, metrics, PublicAPI

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java, ui-tests/src/test/java/io/syndesis/qe/pages/connections/detail/ConnectionDetail.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/resources/features/connections/oauth.feature, ui-tests/src/test/resources/features/integrations/mqtt.feature
=> [FUSEQE-8675] Fixing testsuite against syndesis 2.0

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
//skip-ci
DataTestIds: syndesisio/syndesis#8291
=> [FUSEQE-8681] pf4 migration - specifySecurity

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature, rest-tests/src/test/resources/upgrade/syndesis-cr-previous-externaldb.yaml, utilities/src/main/java/io/syndesis/qe/resource/impl/PreviousSyndesis.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-8652] Add test for upgrade with external DB

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-8611] Rework adding custom repo

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java, ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
=> [FUSEQE-8681][pf4-migration] Extension page improvement

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java, ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java, ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
backport https://github.com/syndesisio/syndesis-qe/pull/1438
=> [backport][FUSEQE-8681][pf4-migration] Extension page improvement

ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/VirtualizationList.java, ui-tests/src/test/java/io/syndesis/qe/pages/Virtualizations/Virtualizations.java, ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java, ui-tests/src/test/resources/features/other/data-virtualization.feature
DataTestIds: https://github.com/syndesisio/syndesis/pull/8319
=> [FUSEQE-8681][pf4-migration] data virt smoke migration

rest-tests/src/test/resources/features/publicapi/connections.feature, rest-tests/src/test/resources/features/publicapi/integrations.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java, utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/ConnectionsPublicEndpoint.java, utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java, utilities/src/main/java/io/syndesis/qe/model/IntegrationOverview.java, utilities/src/main/java/io/syndesis/qe/publicapisteps/ConnectionsPublicApiSteps.java, utilities/src/main/java/io/syndesis/qe/publicapisteps/IntegrationsPublicApiSteps.java
* Reproducers for ENTESB-12885 and ENTESB-13013
* Added test for checking whether a connection was created after the import
* Added test for deploying integration after import
//test: `@ENTESB-13013 or @ENTESB-12885 or @export-import-and-deploy or @export-import-integrations-with-connection-test or @deploy-redeploy-integration`
=> [FUSEQE-8633] Extend PublicApi rest tests

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/datashapes.feature, ui-tests/src/test/resources/features/integrations/integration-status.feature
//test: `@integrations-datashapes or @conditional-flow`
=> [FUSEQE-8681][pf4-migration] Data shapes and conditional flows fixes

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java, ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/integrations/datashapes.feature, ui-tests/src/test/resources/features/integrations/integration-status.feature
//skip-ci
Backports for:
https://github.com/syndesisio/syndesis-qe/pull/1448
https://github.com/syndesisio/syndesis-qe/pull/1440
https://github.com/syndesisio/syndesis-qe/pull/1452
=> [FUSEQE-8681][pf4-migration] Backport to master

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
=> [FUSEQE-8681][pf4-migration] apicurio test

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/state/IntegrationStateHandler.java, rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/ResourceFactory.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
=> [Wait] Move catching exceptions to waitFor method

rest-tests/src/test/resources/features/publicapi/connections.feature, ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java
=> [FUSEQE-8681] - prevent form to use stale elements

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
//test: `@integrations-datashapes-input-change`
=> Use modal page for deleting steps

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
=> [Kafka] Add missing parameter

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
=> (backport master)Use modal page for deleting steps

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature
=> Fixed conditional flow steps

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/resources/features/integrations/api-provider.feature
//test: `@integrations-check-starting-status or @api-provider-create-from-scratch`
=> [FUSEQE-8681] Fix integrations-check test

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
//test: `@api-provider-save-progress`
=> Fix "check there are (\d*) integration steps"

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java, ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/java/io/syndesis/qe/utils/UIUtils.java, ui-tests/src/test/resources/features/customizations/extension-CRUD.feature, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/conditional-flow.feature
//skip-ci
Backports for:
https://github.com/syndesisio/syndesis-qe/pull/1465
https://github.com/syndesisio/syndesis-qe/pull/1464
https://github.com/syndesisio/syndesis-qe/pull/1462
https://github.com/syndesisio/syndesis-qe/pull/1461
https://github.com/syndesisio/syndesis-qe/pull/1460
=> [FUSEQE-8681] - backports PF4 changes

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@logout-test-logout-login`
=> [FUSEQE-8675] Fix testsuite to syndesis 2.0 part 2

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
Should be the only fix API related tests fail on once https://github.com/syndesisio/syndesis/pull/8492 gets merged
=> [fix] added test ids to choose api method page

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
//skip-ci 
backport of https://github.com/syndesisio/syndesis-qe/pull/1477
=> [backport][fix] added test ids to choose api method page

utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
=> [ResetDB] Reset DV when it is present

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java, ui-tests/src/test/resources/features/integrations/dynamodb.feature, ui-tests/src/test/resources/features/integrations/google-sheets.feature, ui-tests/src/test/resources/features/other/integration-activity.feature
* Added support for same field name in the different data buckets
* Migrated conditional flow
* Added blocker annotation
//test: `@dynamodb-query or @integrations-conditional-flows`
=> [FUSEQE-8862] Support for fields with the same name in DataMapper

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [Deploy] Use new variable names for images

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
=> [Upgrade] Sort tags before selecting the latest one

ui-tests/src/test/java/io/syndesis/qe/steps/other/KafkaSteps.java, ui-tests/src/test/resources/features/integrations/db-to-kafka-secure.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/Kafka.java, utilities/src/main/java/io/syndesis/qe/utils/KafkaUtils.java
kafka security enhancement test
//test: `@db-to-kafka-to-db-secure`
=> [FUSEQE-8568] Automation test for kafka TSL

ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
//skip-ci
DataTestId: https://github.com/syndesisio/syndesis/pull/8524
=> Add DataTestId to the Api review page

ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java, ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
=>  Add DataTestId to the Api review page 

ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
=> Added ENTESB annotation

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/java/io/syndesis/qe/steps/other/MongoDBSteps.java, ui-tests/src/test/resources/features/integrations/slack.feature, ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature, ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-5584] Test maximum number of integrations

ui-tests/src/test/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java, ui-tests/src/test/resources/features/other/docs-verification.feature
//test: `@docs-verification`
`@ENTESB-13763`
=> [FUSEQE-3846] Backport to master

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
=> Fix enabling test support on operator DC

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/resources/features/integrations/google-sheets.feature
=> [FUSEQE-8862] Change datatestid for properties

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
=> [Upgrade] Fix deploying previous released image

ui-tests/src/test/resources/features/integrations/api-provider.feature
=> API Provider data mapper tests & error rename

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/resources/features/integrations/openapi.feature
=> Fix api provider selector

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java, ui-tests/src/test/java/io/syndesis/qe/utils/ByUtils.java, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/openapi.feature
//skip-ci
Backports for:
https://github.com/syndesisio/syndesis-qe/pull/1466
https://github.com/syndesisio/syndesis-qe/pull/1498
https://github.com/syndesisio/syndesis-qe/pull/1499
=> Backport master

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
//skip-ci
Clean up dv server after dv tests to prevent affect the other tests.
=> Clean up DV server after dv test

ui-tests/src/test/resources/features/integrations/api-provider.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
//test: `@api-provider-openapi-edit-implemented or @api-provider-post-new`
=> API Provider datamapper and wait fix

utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
=> [Operator] Fix volume tests

rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java, rest-tests/src/test/resources/features/disconnected-install.feature, ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/other/data-virtualization.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java, utilities/src/main/java/io/syndesis/qe/hooks/TestHooks.java, utilities/src/main/java/io/syndesis/qe/resource/impl/WildFlyS2i.java
//test: `@disconnected-install and not @camel-k`
=> [FUSEQE-8553] Add more disconnected install scenarios

ui-tests/src/test/resources/features/customizations/connectors/webhook.feature, ui-tests/src/test/resources/features/other/integration-activity.feature
* Updated activity error tests according to webhook changes
* Reproducers for webhook changes
//skip-ci
backport for https://github.com/syndesisio/syndesis-qe/pull/1510
=> [FUSEQE-9292] Update activity error tests

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/spec/components/server/mavenRepositories-append.yml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
//skip-ci
needs a new daily build after 2.6.
=> Append repositories

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/spec/components/server/mavenRepositories-append.yml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
//skip-ci
needs a new daily build after 2.6.
=> Append repositories master

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
=> Hotfix for datamapper

ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
=> FUSEQE-9312 Fix 10-integrations-complex test and replace odata with servicenow

ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature
=> Remove odata server from maxIntegrations test

ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/db-to-kafka-secure.feature
=> Fix undefined step after refactoring

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java, rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
=> [Upgrade] Remove rollout after upgrade

ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java
=> Fix DV UI for 7.7

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/spec/addons/camelk.yml, rest-tests/src/test/resources/operator/spec/addons/external-jaeger.yml, rest-tests/src/test/resources/operator/spec/addons/jaeger.sampler.yml, rest-tests/src/test/resources/operator/spec/addons/jaeger.yml, rest-tests/src/test/resources/operator/spec/backup-external-db.yml, rest-tests/src/test/resources/operator/spec/backup.yml, rest-tests/src/test/resources/operator/spec/components/database/externalDb.yml, rest-tests/src/test/resources/operator/spec/components/server/deployIntegrations.yml, rest-tests/src/test/resources/operator/spec/components/server/integrationLimit.yml, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
=> [Operator] Fix maven repositories in operator tests

rest-tests/src/test/resources/features/operator-deployment.feature, rest-tests/src/test/resources/operator/spec/addons/camelk.yml, rest-tests/src/test/resources/operator/spec/addons/external-jaeger.yml, rest-tests/src/test/resources/operator/spec/addons/jaeger.sampler.yml, rest-tests/src/test/resources/operator/spec/addons/jaeger.yml, rest-tests/src/test/resources/operator/spec/backup-external-db.yml, rest-tests/src/test/resources/operator/spec/backup.yml, rest-tests/src/test/resources/operator/spec/components/database/externalDb.yml, rest-tests/src/test/resources/operator/spec/components/server/deployIntegrations.yml, rest-tests/src/test/resources/operator/spec/components/server/integrationLimit.yml, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
=> Fix repositories master

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java, ui-tests/src/test/resources/features/customizations/extension-CRUD.feature, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/other/data-virtualization.feature, utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
=> Remove Sync time with integration pod

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/resources/features/other/camelk.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
=> [ui][camelk] Added CamelK smoke test

ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature
=> Move the waiting steps in 10-integration test

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/OperatorMeteringLabels.java, rest-tests/src/test/resources/features/check-metering-labels.feature
=> [FUSEQE-9074] create automated tests for ENTESB-12882

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/OperatorMeteringLabels.java, rest-tests/src/test/resources/features/check-metering-labels.feature
=> Backport - [FUSEQE-9074] create automated tests for ENTESB-12882

ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java, ui-tests/src/test/resources/features/other/camelk.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java
=> (backport) [ui][camelk] Added CamelK smoke test

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java, ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/WizardSteps.java, ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature, ui-tests/src/test/resources/features/integrations/api-provider.feature, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
//test: `@api-client-auth-api-key-headers or @api-client-auth-api-key-query or @openapi-client`
=> [ui] stability fixes

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/datavirtualization/DataVirtualizationSteps.java, ui-tests/src/test/resources/features/customizations/extension-CRUD.feature, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/other/data-virtualization.feature, ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature, utilities/src/main/java/io/syndesis/qe/hooks/TestHooks.java, utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
* added timeout after deleting extension
* fixed reset DV
* added all failed build to the log
//skip-ci
Backport for 
https://github.com/syndesisio/syndesis-qe/pull/1529
https://github.com/syndesisio/syndesis-qe/pull/1530
https://github.com/syndesisio/syndesis-qe/pull/1537
=> Backports master

utilities/src/main/java/io/syndesis/qe/hooks/TestHooks.java
=> [FUSEQE-9413] Add all failed build to the log

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/resources/syndesis-minimal.yaml
=> [Deploy] Add demoData: true to have the sampleDB connection

rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
=> [Upgrade] List all tags from docker hub

ui-tests/src/test/resources/features/other/data-virtualization.feature, ui-tests/src/test/resources/features/other/support-page.feature, utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java, utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java
//test: `@activity-test`
Revert https://github.com/syndesisio/syndesis-qe/pull/1529
=> Remove gh issue from issue hooks

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/AddToIntegration.java, ui-tests/src/test/resources/features/integrations/api-provider.feature, ui-tests/src/test/resources/features/integrations/data-mapper.feature
//test: `@api-provider-finish-replace or @data-mapper-reconfigure or @api-provider-post-existing`
=> [ui] Added regressions tests for several issues

pom.xml, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/fhir/Create.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/connection/fhir/FhirSteps.java, ui-tests/src/test/resources/features/integrations/fhir.feature, ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature, ui-tests/src/test/resources/features/other/support-page.feature, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/FhirValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/FHIR.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirEntity.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirUtils.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/MyBasicSpecification.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/MyPatientClient.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/MyPatientSpecification.java
//test: `@fhir`
lasting problems:
1. @fhir-2-patch, see TODO
2. Fhir Client connection unstability.
Client connection is extremely unstable. (see `FhirUtils.checkConnection()`, TODO)
and even renewed before each usage, it keeps failing on:
`ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing GET to URL http://localhost:8082/baseDstu3/Patient`
This problem seems to be related to our testsuite, (probably st. to do with `Given clean application state`) because if you run fhir-client in separate project, stability is OK.
=> [FUSEQE-2296] Fhir connector test

ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/resources/features/integrations/fhir.feature, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/FHIR.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirUtils.java
Resolved problems from this PR https://github.com/syndesisio/syndesis-qe/pull/1533
* Improve FHIR#isReady and FHIR#udeploy method, change FHIR server name
* Make FhirClientManager singleton
* Add hook for undeploy FHIR and close PORT FORWARD
* Add workaround for Patch operation
//test: `@fhir`
=> Resolve lasting problems with FHIR tests

pom.xml, ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/fhir/Create.java, ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/connection/fhir/FhirSteps.java, ui-tests/src/test/resources/features/integrations/fhir.feature, ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature, ui-tests/src/test/resources/features/other/support-page.feature, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/FhirValidationSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/FHIR.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirClientManager.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirEntity.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/FhirUtils.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/MyBasicSpecification.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/MyPatientClient.java, utilities/src/main/java/io/syndesis/qe/utils/fhir/MyPatientSpecification.java
=> Backport FHIR to master

utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
=> [HTTPS] Add jackson parameter to JAVA_OPTIONS

utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
This reverts commit c899f9761975b7e2208dbb434ae8ddafedc65ad6.
//skip-ci
=> Revert "[Operator] Fix volume tests"

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> [Jackson] Whitelist packages by default

docker/Dockerfile, docker/credentials_minimal.json, docker/syndesisQe.sh, docker/syndesisQe_delorean.sh, rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java, rest-tests/src/test/resources/features/file-transfer.feature, rest-tests/src/test/resources/features/integration-aggregate.feature, rest-tests/src/test/resources/features/integration-database.feature, rest-tests/src/test/resources/features/integration-edit-dc.feature, rest-tests/src/test/resources/features/integration-lifecycle.feature, rest-tests/src/test/resources/features/integration-monitoring.feature, rest-tests/src/test/resources/features/irc.feature, rest-tests/src/test/resources/features/timer-connector.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/SyndesisDB.java, utilities/src/main/resources/templates/syndesis-sampledb-config.yml
Docker file for building REST test suite image for us or delorean team was created
The support for running test suite in the environment where is set external db (only for REST now)
Cleaning integration in Delorean environment (where TEST SUPPORT is not set)
=> [FUSEQE-9017] Containerizing test suite

docker/Dockerfile, docker/credentials_minimal.json, docker/syndesisQe.sh, docker/syndesisQe_delorean.sh, rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java, rest-tests/src/test/resources/features/file-transfer.feature, rest-tests/src/test/resources/features/integration-aggregate.feature, rest-tests/src/test/resources/features/integration-database.feature, rest-tests/src/test/resources/features/integration-edit-dc.feature, rest-tests/src/test/resources/features/integration-lifecycle.feature, rest-tests/src/test/resources/features/integration-monitoring.feature, rest-tests/src/test/resources/features/irc.feature, rest-tests/src/test/resources/features/timer-connector.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/accounts/Account.java, utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java, utilities/src/main/java/io/syndesis/qe/resource/impl/SyndesisDB.java, utilities/src/main/resources/templates/syndesis-sampledb-config.yml
Backport for https://github.com/syndesisio/syndesis-qe/pull/1560
=>  [FUSEQE-9017] Containerizing test suite

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
Support the case when the Syndesis is installed via OperatorHub
=> Fix enableTestSupport method

utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
=> [Hooks] Fix wrong assumption in issue hook

pom.xml
=> [Cluecumber] Expand step hooks by default

ui-common/src/main/java/io/syndesis/qe/hooks/UITestsHooks.java
=> [FUSEQE-9926] Include browser console log

ui-common/src/main/java/io/syndesis/qe/hooks/UITestsHooks.java, utilities/src/main/java/io/syndesis/qe/hooks/TestHooks.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
=> Improve cucumber report

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, operator-tests/src/test/resources/features/operator-deployment.feature, operator-tests/src/test/resources/operator/spec/components/server/additionalMavenArguments.yml, validation/src/main/java/io/syndesis/qe/validation/OpenshiftValidationSteps.java
=> [ENTESB-14068] Add ENTESB-14068 reproducer

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [Deploy] Check for all necessary values in route

ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java, ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/integrations/template.feature
=> [FUSEQE-9954] Fixes for 1.11.x

upgrade-tests/src/test/resources/features/upgrade.feature, utilities/src/main/java/io/syndesis/qe/utils/PortForwardUtils.java
=> [FUSEQE-9963] Fix port-forwarding issues + add annotation

ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
//test: `@create-api-connector-from-url-test or @api-client-auth-api-key-query or @api-client-auth-api-key-headers`
=> Change url for petstore swagger

endpoints/pom.xml, endpoints/src/main/java/io/syndesis/qe/endpoint/client/EndpointClient.java, pom.xml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
needed for https://github.com/syndesisio/syndesis/pull/8921
//skip-ci
=> [FUSEQE-14310] Bump resteasy version

ui-tests/src/test/resources/features/connections/oauth.feature, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/customizations/extension-CRUD.feature, ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature, ui-tests/src/test/resources/features/integrations/data-buckets.feature, ui-tests/src/test/resources/features/integrations/db-to-kafka-secure.feature, ui-tests/src/test/resources/features/integrations/db-to-kafka.feature, ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature, ui-tests/src/test/resources/features/integrations/fhir.feature, ui-tests/src/test/resources/features/integrations/import-edit.feature, ui-tests/src/test/resources/features/integrations/kudu.feature, ui-tests/src/test/resources/features/integrations/mqtt.feature, ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature, ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature, ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature, ui-tests/src/test/resources/features/other/login-logout.feature, ui-tests/src/test/resources/features/other/settings-oauth.feature, ui-tests/src/test/resources/features/other/support-page.feature
=> sustainers update

ui-tests/src/test/resources/features/connections/oauth.feature, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/customizations/extension-CRUD.feature, ui-tests/src/test/resources/features/integrations/amqp-to-amqp.feature, ui-tests/src/test/resources/features/integrations/data-buckets.feature, ui-tests/src/test/resources/features/integrations/db-to-kafka-secure.feature, ui-tests/src/test/resources/features/integrations/db-to-kafka.feature, ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature, ui-tests/src/test/resources/features/integrations/fhir.feature, ui-tests/src/test/resources/features/integrations/import-edit.feature, ui-tests/src/test/resources/features/integrations/kudu.feature, ui-tests/src/test/resources/features/integrations/mqtt.feature, ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature, ui-tests/src/test/resources/features/integrations/sftp-to-sftp.feature, ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature, ui-tests/src/test/resources/features/other/login-logout.feature, ui-tests/src/test/resources/features/other/settings-oauth.feature, ui-tests/src/test/resources/features/other/support-page.feature
=> backport-sustainers-update

pom.xml, upgrade-tests/pom.xml, upgrade-tests/src/test/java/io/syndesis/qe/CucumberRunner.java, upgrade-tests/src/test/java/io/syndesis/qe/UpgradeSteps.java, upgrade-tests/src/test/resources/features/upgrade-ui.feature
=> [FUSEQE-5557] Create an UI test for upgrade

ui-tests/src/test/resources/features/other/docs-verification.feature
=> Prod tag added

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, ui-tests/src/test/resources/features/other/docs-verification.feature
backport to master
//test: `@docs-verification` , `@check-metering-labels`
=> Backport labels and prod tag

ui-common/src/main/java/io/syndesis/qe/hooks/UITestsHooks.java
=> [FUSEQE-10127] Scale down screenshots

ui-tests/src/test/resources/features/integrations/odata.feature
//test: `@odata or @odata-server-certificate`
=> Fix OData connection

utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
=> Fix wait for Jaeger operator in the second namespace

ui-common/src/main/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java, ui-common/src/main/java/io/syndesis/qe/steps/customizations/connectors/detail/DetailSteps.java, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/integrations/odata.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/CamelK.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java, utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
//skip-ci
Backport for:
https://github.com/syndesisio/syndesis-qe/pull/1599
https://github.com/syndesisio/syndesis-qe/pull/1596
https://github.com/syndesisio/syndesis-qe/pull/1601
=> Backport OData, Jaeger and API connector fixes

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, operator-tests/src/test/resources/features/operator-deployment.feature, operator-tests/src/test/resources/operator/spec/addons/dv.yml, operator-tests/src/test/resources/operator/spec/components/database/externalDb.yml, operator-tests/src/test/resources/operator/spec/components/database/volumeAccessModes.yml, operator-tests/src/test/resources/operator/spec/components/database/volumeCapacity.yml, operator-tests/src/test/resources/operator/spec/components/database/volumeStorageClass.yml, operator-tests/src/test/resources/operator/spec/components/meta/volumeAccessModes.yml, operator-tests/src/test/resources/operator/spec/components/meta/volumeCapacity.yml, operator-tests/src/test/resources/operator/spec/components/meta/volumeLabels.yml, operator-tests/src/test/resources/operator/spec/components/meta/volumeName.yml, operator-tests/src/test/resources/operator/spec/components/meta/volumeStorageClass.yml, operator-tests/src/test/resources/operator/spec/components/prometheus/volumeAccessModes.yml, operator-tests/src/test/resources/operator/spec/components/prometheus/volumeCapacity.yml, operator-tests/src/test/resources/operator/spec/components/prometheus/volumeLabels.yml, operator-tests/src/test/resources/operator/spec/components/prometheus/volumeName.yml, operator-tests/src/test/resources/operator/spec/components/prometheus/volumeStorageClass.yml, operator-tests/src/test/resources/operator/spec/components/resources.limits.memory.yml, utilities/src/main/java/io/syndesis/qe/utils/PortForwardUtils.java
=> [FUSEQE-13622/13623] Add reproducers

rest-common/src/main/java/io/syndesis/qe/steps/connection/Connections.java, rest-tests/src/test/resources/features/integration-kafka.feature, validation/src/main/java/io/syndesis/qe/validation/KafkaValidationSteps.java
=> [ENTESB-13846] Add ENTESB-13846 reproducer

ui-common/src/main/java/io/syndesis/qe/steps/other/KafkaSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Kafka.java
//skip-ci
Removed code for creating/deleting ClusterRole. It is not needed anymore. https://issues.redhat.com/browse/ENTESB-14507
=> [FUSEQE-10188] - fix Kafka tests

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
=> [SingleUser] Dont check for permissions with single user

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> [SingleUser] Check the actual value of property

upgrade-tests/src/test/java/io/syndesis/qe/UpgradeSteps.java
=> [Upgrade] Fix previous version parsing

docker/entrypoint.sh
=> [Docker] Fix secret creation and handle failures

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [Deploy] Retry operations when updating dc

ui-common/src/main/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java, ui-common/src/main/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@log-connector-no-message`
=> [FUSEQE-10209] Make connector test stable + fix all credentials test

utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
=> [FUSEQE-10351] Retry downloading binary client

.mvn/wrapper/maven-wrapper.properties
=> [FUSEQE-10352] Bump maven version

upgrade-tests/src/test/resources/features/upgrade-ui.feature
=> [Upgrade] Rename UI upgrade scenario

utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java
=> Improve isReady in PublicOauthProxy

README.md
=> Fix in debugging command 

README.md
=> Backport to master - fix in debugging command

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, upgrade-tests/src/test/java/io/syndesis/qe/UpgradeSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/PreviousSyndesis.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [Deploy] Replace deployCrd with installCluster

pom.xml
//skip-ci
merge after https://github.com/syndesisio/syndesis/pull/9141
=> [POM] Sync spring version with syndesis

.mvn/wrapper/maven-wrapper.properties, rest-tests/src/test/resources/features/integration-sqs.feature, validation/src/main/java/io/syndesis/qe/validation/HTTPValidationSteps.java, validation/src/main/java/io/syndesis/qe/validation/SQSValidationSteps.java
//test: `@integration-sqs-sqs-max-objects or @integration-http-consumer-delete`
=> [Fixes] Fix editing DC and polling SQS

ui-common/src/main/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
=> Fix webhook return code

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/ExternalDatabase.java, utilities/src/main/java/io/syndesis/qe/resource/impl/PreviousSyndesis.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> fixes master

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, operator-tests/src/test/resources/features/operator-deployment.feature, operator-tests/src/test/resources/operator/spec/affinityInfra.yml, operator-tests/src/test/resources/operator/spec/affinityIntegration.yml, operator-tests/src/test/resources/operator/spec/tolerationsInfra.yml, operator-tests/src/test/resources/operator/spec/tolerationsIntegration.yml, utilities/src/main/java/io/syndesis/qe/utils/PortForwardUtils.java
=> [ENTESB-13803] Add affinity and tolerations tests

ui-tests/src/test/resources/features/integrations/conditional-flow.feature, ui-tests/src/test/resources/features/other/support-page.feature
//skip-ci
Backport for https://github.com/syndesisio/syndesis-qe/pull/1646
=> Fix webhook in conditional flow and revert RP dummy tests

rest-tests/src/test/resources/features/disconnected-install.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/MongoDb36.java
=> [FUSEQE-8553] Remove tests that need external access

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> Use default cr for particular version

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, operator-tests/src/test/resources/features/check-metering-labels.feature
Now it checks the value of each metering label.
=> Metering labels test update

utilities/src/main/java/io/syndesis/qe/resource/impl/SFTP.java
=> [SFTP] Add pull secret to sftp SA

utilities/src/main/java/io/syndesis/qe/resource/impl/SFTP.java
=> Fix SFTP test

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [Deploy] Refactor operator deployment

README.md, pom.xml, utilities/pom.xml, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java, utilities/src/main/java/io/syndesis/qe/common/CommonSteps.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> [FUSEQE-10617] Operatorhub automation

ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java, ui-tests/src/test/resources/features/other/docs-verification.feature
=> check latest released version

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> Fix deploying Syndesis on 3.11

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> Remove xtf property for oc version specification

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> Fix permission

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
=> Revert xtf version

ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java
=> [FUSEQE-10718] Update documentation verification test 

ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java, ui-tests/src/test/resources/features/other/docs-verification.feature
=> BACKPORT [FUSEQE-10718] Update documentation verification test 

ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java
=> docs-verification test update

ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java
=> Backport - docs-verification test update

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java
=> Support 3.11 for affinity tests

utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
+ skip admin permission check for default kube:admin on crc 
//skip-ci
=> Fix deploying Syndesis on minishift

pom.xml
=> [POM] Bump junit version

docker/Dockerfile, docker/entrypoint.sh
=> [Docker] Changes for 1.12.x

docker/Dockerfile, docker/entrypoint.sh
=> [Docker] Make docker work with 1.11.x

ui-common/src/main/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/resources/features/other/3scale.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
=> [3scale] Add changes required for 3scale service discovery testing

pom.xml, utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
//skip-ci
to be merged after https://github.com/syndesisio/syndesis/pull/9231
=> [Deploy] Replace deploymentconfig with deployment

ui-common/src/main/java/io/syndesis/qe/steps/CommonSteps.java, ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature, ui-tests/src/test/resources/features/integrations/fhir.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
//test: `@ENTESB-15292`
@fhir-2-2-patch is failing till PR for ENTESB-14237 will be closed
=> Reproducer for ENTESB-15292 and ENTESB-14237

operator-tests/src/test/resources/operator/spec/addons/jaeger-external.yml, operator-tests/src/test/resources/operator/spec/addons/jaeger-hybrid.yml, operator-tests/src/test/resources/operator/spec/addons/jaeger.sampler.yml, operator-tests/src/test/resources/operator/spec/addons/jaeger.yml, operator-tests/src/test/resources/operator/spec/affinityInfra.yml, operator-tests/src/test/resources/operator/spec/affinityIntegration.yml, operator-tests/src/test/resources/operator/spec/components/server/additionalMavenArguments.yml, operator-tests/src/test/resources/operator/spec/components/server/integrationLimit.yml, operator-tests/src/test/resources/operator/spec/components/server/mavenRepositories-append.yml, operator-tests/src/test/resources/operator/spec/components/server/mavenRepositories.yml, operator-tests/src/test/resources/operator/spec/tolerationsInfra.yml, operator-tests/src/test/resources/operator/spec/tolerationsIntegration.yml, ui-common/src/main/java/io/syndesis/qe/steps/other/DocsVerificationSteps.java, ui-common/src/main/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java, ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java, ui-tests/src/test/resources/features/other/camelk.feature, utilities/src/main/java/io/syndesis/qe/resource/impl/Ops.java, utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java, validation/src/main/java/io/syndesis/qe/validation/MongoDBValidationSteps.java, validation/src/main/java/io/syndesis/qe/validation/OpsValidationSteps.java
* @disabled for CamelK
* Change syndesis-operator DC to Deplment in OPS tests
* Add list of routes to the getUrlForWebhook when particular route doesn't exist
* Increase version for docs test
* Fix After hooks
* Add demoData to the OperatorTests CRs
//skip-ci
=> [FUSEQE-11267] - Fixes for 1.12.x

pom.xml, ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
=> Up the atlasmap version

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
=> Fix upgrade test

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java, operator-tests/src/test/resources/features/operator-deployment.feature, pom.xml, ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java, ui-common/src/main/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java, ui-common/src/main/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java, ui-common/src/main/java/io/syndesis/qe/steps/other/ServiceNowSteps.java, ui-tests/src/test/resources/features/integrations/fhir.feature, ui-tests/src/test/resources/features/integrations/google-sheets.feature, ui-tests/src/test/resources/features/soak-deployments/maxIntegrations.feature, utilities/src/main/java/io/syndesis/qe/TestConfiguration.java, utilities/src/main/java/io/syndesis/qe/resource/impl/Jaeger.java, utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java, validation/src/main/java/io/syndesis/qe/validation/ServiceNowValidationSteps.java
* Remove reproducers for won't fix issue
* Fix DataMapper property
* Change DataMapper property to DataMapper constant since properties work differently now
* Fix incorrect parallelization for servicenow in maxIntegratiosn test
* Fix for external jaeger
//skip-ci
=> Fixes after DataMapper update

ui-tests/src/test/resources/features/customizations/connectors/api-client-authentication.feature
//test: `@api-client-auth-basic-password`
=> [FUSEQE-7152] API client authentication - basic password
