syndesisio/syndesis-qe

Jenkinsfile

This declaration is not need anymore as we have pipeline declared in job itself.

ci: remove pipeline library declaration

---

e2e-xvfb.sh
package.json

webdriver update should be run automatically this way
```bash
$ yarn e2e:syndesis-qe -- --cucumberOpts.tags="@datamapper" 
yarn e2e:syndesis-qe v0.24.6
$ webdriver-manager update
[15:21:06] I/update - chromedriver: file exists /home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.30.zip
[15:21:06] I/update - chromedriver: unzipping chromedriver_2.30.zip
[15:21:06] I/update - chromedriver: setting permissions to 0755 for /home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.30
[15:21:06] I/update - chromedriver: chromedriver_2.30 up to date
[15:21:06] I/update - selenium standalone: file exists …
```

[webdriver] Run webdriver manager update automagically

---

e2e/conf/protractor.base.conf.js
package.json
yarn.lock

This PR resolves #26.
`protractor-console-plugin` should provide simple mechanism how error and warning logs are reported back during E2E tests. It should be sufficient for now and we can upgrade to asserting browser logs later.

chore: Add protractor-console-plugin to catch browser logs

---

Jenkinsfile

It's needed as a result of new screenshot dir created in #63.

Add subdirs to archived results

---

README.md
e2e/settings/settings.feature
e2e/settings/settings.po.ts
e2e/settings/settings.steps.ts

@mmelko @lvydra @dsimansk 
This is very basic test for settings page.
I didn't do deleting of settings as it throws HTTP500 (reported as syndesis-rest/issues#549)
and it wasn't clear how it was supposed to work.
Delete settings is TODO for future

[closes #34] Implement basic test for oauth settings page

---

Jenkinsfile

This keeps at most 5 builds/artifacts in order to preserve disk space on
Jenkins.

chore(build): Discard old builds

---

ui-tests-protractor/e2e/app.po.ts
ui-tests-protractor/e2e/common/common.steps.ts

This is a bit naive, but seems to work fine.

fix: Reset state via browser to preserve auth cookie

---

ui-tests-protractor/package.json

Since the update of karma-xvfb image, this should be fine with latest WebDriver version.

chore: Rm WebDriver version lock

---

ui-tests-protractor/e2e/integrations/edit/datamapper.po.ts

Top entries are too close to top bars, which is un-clickable.

fix: Fix Datamapper field click too close to top

---

ui-tests-protractor/e2e/common/common.steps.ts
ui-tests-protractor/e2e/conf/protractor.base.conf.js
ui-tests-protractor/e2e/integrations/integrations-sf-db.feature
ui-tests-protractor/package.json
ui-tests-protractor/yarn.lock

Overall stability improvements
- remove protractor-console-plugin as it's not doing desired reports
- increase timeout for dynamic dropdowns to 30s
- move clean in SF DB scenario for constistency

Stability improvements

---

ui-tests-protractor/e2e/app.po.ts

Avoid situation that other variant of e.g. `Contact ...` is selected. Also it seems to be more stable for TwitterScreenName.

fix: Match the exact text in dropdown select

---

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java

WDYT?
Getting rid of former AppPage and moving general methods like findButton(), clickButton() etc on abstract ancestor class. Then this methods will be available on root element of every descendant page object.

General ancestor for syndesis java page objects

---

pom.xml
rest-tests/pom.xml
rest-tests/src/test/java/io/syndesis/qe/rest/RestTestSuite.java
rest-tests/src/test/java/io/syndesis/qe/rest/tests/CucumberTestsRunner.java
rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/CommonSteps.java
rest-tests/src/test/resources/features/common.feature
ui-tests/pom.xml
utilities/pom.xml
utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java

This PR adds simple BDD test that for the given namespace tries to clean&deploy Syndesis.
Note that I've changed Cucumber dependencies to latest version. There was org-id change hence the bigger change in poms.
With proper test.properties PoC is runnable like:
`mvn clean test -P rest -Dtest=CucumberTestsRunner -Dcucumber.options="--tags @clean-deploy"`

chore: Add BDD example to rest-tests

---

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java

A small disclaimer: I've deliberately kept `resetState()` via browser as a reference.

Clean state via backend & verification in SF to DB

---

pom.xml
ui-tests/pom.xml
ui-tests/src/test/java/io/syndesis/qe/hooks/OnFailHooks.java

When going through nightly builds every day I figured out that something like this may be beneficial. Now I can see if the scenario which failed has some opened issues and I can do fast check if the reason of failure is already reported (in case of bug). This will also prevent second investigation if we forget that the issue already exists and the possibility to check resolved issues if we had previously similar problem with failed scenario. WDYT?

[ui] Adding issue library to inform via console about known issues

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/BasicFilter.java
ui-tests/src/test/java/io/syndesis/qe/steps/other/SlackSteps.java
ui-tests/src/test/resources/features/integrations/slack.feature
utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java

- The test for the Slack consumer was added
- The CSS selectors in the BasicFilter were updated
- SlackConnector was updated according to updated [credentials](https://gitlab.cee.redhat.com/jboss-fuse-qe/ci-ops-fuse/commit/2fea1870138ebdbde9da859f3ac36fb1c851ac94?merge_request_iid=146). 
//test: @slack-to-db

[ui][new] adding test for Slack consumer

---

rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntermediateSteps.java

Fixing missing flow id when creating Integration.
Doesn't affect tests really, only issue was viewing the Integration created by REST tests.
Also noticed that Rule Filters don't have name specified, fixing that.

[rest][fix] add missing flow id + name to filter

---

ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
utilities/src/main/java/io/syndesis/qe/TestConfiguration.java

I needed to launch Chromium instead of Chrome, so I introduced a new
configuration property `syndesis.config.browser.path` to point to the
browser executable.
Can be used as:
./mvnw test -Dsyndesis.config.browser.path=/usr/bin/chromium-browser

chore: configurable browser binary path

---

ui-tests/src/test/resources/features/integrations/concur.feature

//skip-ci
Skipping tests as they do not work for now - our concur credentials do not have correct permissions to access SAP concur instance endpoints, resulting in 403 error.

[ui][fix] remove outdated step in concur feature

---

ui-tests/src/test/resources/features/integrations/kudu.feature

//test: `@integrations-kudu-scan`

[ui][fix] change to log connector in kudu tests due to removal of log step

---

ui-tests/src/test/resources/features/integrations/kudu.feature

//test: `@integrations-kudu-scan`

[ui][fix] change to log connector in kudu tests due to removal of log step 16x

---

utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java

[ui][fix] kudu tests - do not fail with empty pod logs

---

utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java

[ui][fix] kudu tests - do not fail with empty pod logs 16x

---

rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
utilities/src/main/java/io/syndesis/qe/issue/IssueState.java
utilities/src/main/java/io/syndesis/qe/issue/SimpleIssue.java

This is an initial implementation of showing open issues in emailed test report.
The basic idea is that there's a custom cucumber formatter that generates almost the whole report (except for some headers etc, which will need to be done exernally, since they need to know about the jenkins build info).
There are two main uglies in this:
1. We already check open issues in `IssueHooks.java`, so to prevent hitting github and zenhub twice for each failure, we embed the downloaded issues into the scenario and then retrieve it when creating the report. This does not seem to cause any trouble for the html report, but is not particularly nice. We might decide that requesting the issues twice is preferable
2. The report is currently built by appending to a `StringBuilder`, we might decide we want to …

Add cucumber formatter for mail report

---

ui-tests/pom.xml

so that they are not re-downloaded when using `mvn test`
//skip-ci

[Drivers] Bind drivers download to install phase

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java

I returned the `DataMapper#openDataMapperCollectionElement` back into `create data mapper mappings` step so that any collections we can find on the data mapping view are opened automatically when we try to create the mapping.
It was previously like that before and was removed for the unknown reason, so I put it back to fix the UI tests with SQL connector collections problems.
Here it also checks that collection is not yet open by looking only for `.fa-angle-right` arrow and clicking it. Opened collections have `.fa-angle-down` arrow.

[FUSEQE-4498] fix tests with sql connector mapping collections

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java

we don't want to open all collections automatically - only unnamed ones
if we automatically open all collections, there might be field names collision
on the contrary, if we want to open *all* collections, there is distinct
step for that
//test: `@data-buckets-check-popups or @email-receive or @gmail-receive or @integrations-twitter-to-db`

[UI] only automatically open unnamed collections on data mapper

---

ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java

This fixes the problem with firefox being unable to create a `gmail` connection because clickable area is smaller than the whole connection card firefox is clicking on.
//skip-ci

[UI] fix gmail (and maybe more) connection creation in firefox on react UI

---

ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
ui-tests/src/test/resources/features/integrations/data-buckets.feature

This fixes databucket tests for the new react UI.
The only test that doesn't work yet, is `@data-buckets-usage`, due to datamapper problems (https://github.com/syndesisio/syndesis/issues/5622).
When datamapper bug gets fixed, all databucket tests should pass.
//test: `@data-buckets-check-popups or @data-buckets-usage-2`

[FUSEQE-4299] fix databucket tests with new react UI

---

utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java

Add a check if the openshift cluster is reachable by a simple GET request to the api endpoint in the `resetDB` method as it should be present in (almost) all tests. 
So if the network goes down during a test, the next test will wait (up to 30 minutes) until the api is reachable again, because the current situation is that when the network is down, all tests will fail on resetDB in the matter of seconds :grin:  
There is a slight probability that if the cluster won't respond, the tests will take `countOfTests*30` minutes to finish, but we should notice it sooner :grin: 
@tplevko @asmigala wdyt?

[FUSEQE-4853] Add a simple reachability check

---

utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java

Solves
```
WARNING: A connection to <openshift> was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```
//skip-ci

[Reachability] Close the response body to prevent leaked connections

---

utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java

//test: `@db-connection-crud-2-read-create-oracle12`

Fixed wrong db.schema name from dballocator

---

README.md
utilities/src/main/java/io/syndesis/qe/TestConfiguration.java

Add ability to specify test.properties location

---

ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java

Sometimes the 'Validate all credentials smoke' test fails in PR job. I noticed in the code that we find all forms in the page, filter the particular form and check when the form is there. Probably the page has not been ready yet when the code was looking for the form.
Does we need to do that way? When we know the particular cssClass name for the form, we can just find it.

[UI][fix] - fixed randomly failing 'Validate all credentials' smoke test

---

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
ui-tests/src/test/resources/features/integrations/email.feature

This removes hardcoded email from email tests and allows change of email credentials
//test: `@email`

Fix different credentials working for email connector

---

ui-tests/src/test/resources/features/integrations/api-provider.feature
ui-tests/src/test/resources/features/integrations/sql-connector.feature

//test: `@api-provider-get-collection or @sql-connector-predicates`
Just annotated one of the tests - it's affected by an yet unhandled error response from DB connector and added 2 waits - to solve issue in api-provider-get-collection and sql-connector-predicates.

[fix] post existing - affected by ENTESB-11675, and added 2 waits

---

ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
ui-tests/src/test/resources/features/connections/oauth.feature
ui-tests/src/test/resources/features/integrations/data-buckets.feature
ui-tests/src/test/resources/features/integrations/email.feature
ui-tests/src/test/resources/features/integrations/gmail.feature
ui-tests/src/test/resources/features/integrations/template.feature
utilities/src/main/java/io/syndesis/qe/utils/GMailUtils.java

//test: `@oauth-gmail or @data-buckets-usage or @template-code-editor or @db-template-mustache-file-upload or @db-template-send or @gmail-send or @gmail-receive or @email-send`

[FUSEQE-6054] Remove hardcoded gmail address from tests

---

ui-tests/src/test/resources/features/integrations/api-provider.feature
ui-tests/src/test/resources/features/integrations/template.feature

Added annotations for failing tests

---

ui-tests/src/test/resources/features/integrations/service-now.feature

//test: `@integrations-servicenow`

[servicenow] fix select from dropdowns

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/CiCd/ManageCICDPage.java

[FUSEQE-6350] - added delay to the CICD dialog page

---

ui-tests/src/test/resources/features/customizations/connectors/webhook.feature

[webhook] Fix the webhook regex, to conform to the OCP 4.1. URL format

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java

//test: `@api-provider-create-from-spec`

Add wait for operations to fully load (due to OCP 4.1. failures)

---

ui-tests/src/test/resources/features/integrations/api-provider.feature

//test: `@api-provider-conditional-flow`

[ui] used new steps for interacting with conditional flow

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java

This fixes the error in step `And open data mapper collection mappings` which fails in case no collections are present on the mapper.
//test: `@email-receive`

Fixed the mapper step error in which collections to be opened cannot be found

---

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java

//test: `@3scale or @activity-test`

Fix waiting for server redeployment

---

utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java

Fixes occasional NPE when deploying syndesis:
```
[2019-10-25 09:40:32,487] INFO  [io.syndesis.qe.utils.TodoUtils:29] Creating route todo2 with path /
java.lang.NullPointerException
at io.syndesis.qe.templates.SyndesisTemplate.checkRoute(SyndesisTemplate.java:99)
at io.syndesis.qe.templates.SyndesisTemplate.deploy(SyndesisTemplate.java:53)
at io.syndesis.qe.bdd.CommonSteps.deploySyndesis(CommonSteps.java:66)
```
//skip-ci

[Route] Fix NPE in checkRoute

---

ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
ui-tests/src/test/java/io/syndesis/qe/hooks/ClassTransformerHook.java
ui-tests/src/test/java/io/syndesis/qe/hooks/SelectorSnooper.java

//skip-ci
The testsuite logged that it's generating selector reports even if that wasn't true, also I refactored ClassTransformerHook a bit to make it future proof if we want to add any more transformers.

Classes are transformed only when selector reporting is enabled

---

utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java

//skip-ci
it's *possible* that cleaning up the RCs causes the pods to stay in terminating state *sometimes*

[TestSupport] Revert cleaning RCs

---

rest-tests/src/test/resources/features/soak-deployment.feature
utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
utilities/src/main/java/io/syndesis/qe/utils/JmsClient.java
utilities/src/main/java/io/syndesis/qe/utils/JmsClientManager.java

add autostart of soak scenario
jms client refactor: handle exceptions
jms client refactor: get rid of `autocloseable` and use lambdas we don't need to think about auto closing of jms client when we want to use it outside of `JmsUtils`
//test: `@amqbroker`

add posibility to send message to other than syndesis-amq broker

---

ui-tests/src/test/resources/features/other/support-page.feature

//test: `@support-page-download-diagnostic or @support-page-download-specific-diagnostic`

[FIX] Fix support page tests

---

rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
rest-tests/src/test/resources/features/integration-lifecycle.feature

//skip-ci
skip ci as the whole feature expects stored procedures to be working, but currently they are not, so it would fail anyway

[ENTESB-12493] Add ENTESB-12493 reproducer

---

ui-tests/src/test/resources/features/integrations/google-calendar.feature

//test: `@google-calendar-copy-event or @google-calendar-update-event-coming-in`

[FIX] Fix Google Calendar tests

---

utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java

//test: `@integrations-db-to-db-oracle12`
Expected result of test: fail after 2 mins timeout due to broken dballocator

[FUSEQE-7784] Add read timeout to unsecure rest client

---

ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature

There is only one connector security type and the item cannot be modified
//test: `@integrations-amq-to-rest or @integrations-webhook-api-connector`

[fix] - remove security selection

---

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
ui-tests/src/test/resources/features/integrations/db-to-db.feature
ui-tests/src/test/resources/features/integrations/integration-status.feature
ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature

//test: `@integrations-api-connector`

[fix] annotated db tests and dealt with disabled radiobutton in API client

---

utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java

previously it would only fail with list of pods and message `Wait for Syndesis failed`, now fails with:
```
[2020-03-05 11:20:45,236] ERROR [io.syndesis.qe.bdd.CommonSteps:79] Was waiting for following syndesis components:
[2020-03-05 11:20:46,329] ERROR [io.syndesis.qe.bdd.CommonSteps:80]   syndesis-db
[2020-03-05 11:20:46,330] ERROR [io.syndesis.qe.bdd.CommonSteps:80]   syndesis-oauthproxy
[2020-03-05 11:20:46,330] ERROR [io.syndesis.qe.bdd.CommonSteps:80]   syndesis-prometheus
[2020-03-05 11:20:46,330] ERROR [io.syndesis.qe.bdd.CommonSteps:80]   syndesis-server
[2020-03-05 11:20:46,331] ERROR [io.syndesis.qe.bdd.CommonSteps:80]   syndesis-ui
[2020-03-05 11:20:46,331] ERROR [io.syndesis.qe.bdd.CommonSteps:80]   syndesis-meta
[2020-03-05 11:20:46,331] ERROR …
```

[Deploy] Use CommonSteps#waitForSyndesis to get the info what went wrong

---

ui-tests/src/test/resources/features/connections/oauth.feature
ui-tests/src/test/resources/features/other/settings-oauth.feature

//test: `@settings-oauth-remove-immediately`
explanation: this test fails randomly, because of different network delays. lump time delay should be helpful.

[FIX] Fix @settings-oauth-remove-immediately

---

rest-tests/src/test/resources/features/operator-deployment.feature
ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
ui-tests/src/test/resources/features/other/integration-activity.feature
ui-tests/src/test/resources/features/other/integration-metrics.feature
utilities/src/main/java/io/syndesis/qe/Component.java
utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
utilities/src/main/java/io/syndesis/qe/bdd/validation/OperatorValidationSteps.java
utilities/src/main/java/io/syndesis/qe/resource/impl/PublicOauthProxy.java
utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java
utilities/src/main/java/io/syndesis/qe/utils/CalendarUtils.java

* now, the default-cr.yaml from the fuse online install is used as default CR
* when the docker operator command fails, the whole test suite fail
* Jaeger is used as default activity logging
* add support for generating suffix in the CRC
The test suite will use the `default-cr` from here https://github.com/syndesisio/fuse-online-install/blob/master/default-cr.yml instead of minimal CR from the test suite resources. In case you want to use the one from the resources or `default-cr` from the different branch as master (in the future), you can specify it via `syndesis.config.cr.url`
```
syndesis.config.cr.url=https://raw.githubusercontent.com/syndesisio/syndesis-qe/master/utilities/src/main/resources/syndesis-minimal.yaml
syndesis.config.cr.url=https://raw.githubusercontent.com/syndesisio/fus …
```

[FUSEQE-8028][FUSEQE-8013] - Change default CR and enable Jaeger

---

rest-tests/src/test/resources/features/timer-connector.feature

[fix] Increase timer default time - to achieve more stable results

---

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java

//skip-ci
`waitForSyndesis` is already in the `deploySyndesis` method. I moved the log to that method in order to it is shown in the correct phase.

Log improvement

---

rest-tests/src/test/resources/features/check-prod-versions.feature
utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
utilities/src/main/java/io/syndesis/qe/bdd/validation/ProdValidationSteps.java

//skip-ci
Expects `camel.version` and `syndesis.version` are configured.

[FUSEQE-8506] changed prod test to actually test for the exact value

---

ui-tests/src/test/resources/features/connections/oauth.feature

[FIX] Fix of @oauth-gcalendar test

---

ui-tests/src/test/resources/features/integrations/integration-import-export.feature
ui-tests/src/test/resources/features/integrations/log-connector.feature

//test: `@integration-import-from-different-instance or @log-connector-error-message`

Log connector fixes

---

ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature

//skip-ci
Changed the selector to find only the list items, the test still fails though because of ENTESB-13605

[FUSEQE-8681][pf4-migration] fix @create-delete-api-connector

---

ui-tests/src/test/resources/features/connections/oauth.feature

//test: `@oauth-gcalendar`
fix of @oauth-gcalendar test

[FUSEQE-8797] Fix @oauth-gcalendar test

---

rest-tests/src/test/resources/features/publicapi/connections.feature
ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
ui-tests/src/test/java/io/syndesis/qe/utils/Conditions.java

//test: `@oauth-gcalendar`
Test fix for https://github.com/syndesisio/syndesis-qe/pull/1443

[FUSEQE-8681] - prevent form to use stale elements

---

ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
ui-tests/src/test/resources/features/customizations/extension-CRUD.feature

//test: `@extension-CRUD-delete`

[FUSEQE-8681] Fix extension delete test

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/Template.java

//test: `@template-code-editor`

[FUSEQE-8681] Fix template stale element

---

ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java

[FIX] Fix sveres testsuite

---

utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java

//skip-ci
Fixed a possibility to enable test support via a test suite. It is needed for test suite containerization.
Backports:
https://github.com/syndesisio/syndesis-qe/pull/1493
https://github.com/syndesisio/syndesis-qe/pull/1494

Fix enabling test support on operator DC

---

ui-tests/src/test/resources/features/integrations/api-provider.feature

//test: `@ENTESB-11455`
The response body is null, so checking for it to be empty causes errors, the important detail is the response code.

[ENTESB-11455] Remove verification for non-existant response body

---

rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/OperatorMetricsEndpointSteps.java
ui-tests/src/test/resources/features/integrations/integration-import-export-open-api.feature

//test: `@import-export-open-api`

 Add databuckets in datamapper for API Import/Export test and fix Operator Metrics rest test

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java

* when the constant/property modalDialog is closed, the tooltip for adding, which was opened before, remains open. It may cause instability on chrome. Added click on root element (the tooltip is disappeared)
* clarified log message for Jaeger SA
@mmuzikar  We will see after nightly run whether this change and removing stale elements from `DataMapper#openDataMapperCollectionElement` resolved instability on chrome platform.
```
Element not found {$$(2 elements)[0]}
```

[FUSEQE-9414] improve datamapper instability on Chrome

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java

* when the constant/property modalDialog is closed, the tooltip for adding, which was opened before, remains open. It may cause instability on chrome. Added click on root element (the tooltip is disappeared)
* clarified log message for Jaeger SA

[FUSEQE-9414] Fix datamapper instability on Chrome

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java

//skip-ci
DM select the field with contains, it caused the failure that when the user wants to map `text` field and DM contains e.g. following fields
```
text
field2text
text22
```
Also, there cannot be used equal method, because fields in the property data bucket contains also default value in the name e.g.
```
text = default
```

[hotfix] datamapper

---

ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
ui-tests/src/test/resources/features/integrations/fhir.feature

* Fixed collection name collision in DataMapper.
//skip-ci
Fix FHIR tests according to changes in DataMapper ( https://github.com/syndesisio/syndesis-qe/pull/1550 )
Fixed collection name collision in DataMapper.
E.g. when `id` collection should be selected, more names met the condition, e.g.  `id` and `identifier` , which caused the failure.
Now, the collection name is directly specified in DataTestId

Fix FHIR tests according to changes in DataMapper

---

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java

[FUSEQE-14398] Adopt the new label format for Fuse Online

---

ui-tests/src/test/resources/features/integrations/conditional-flow.feature
ui-tests/src/test/resources/features/other/support-page.feature

//skip-ci
Fixed the conditional flow test + reverted the dummy tests which were accidentally added by this PR https://github.com/syndesisio/syndesis-qe/pull/1638

Fix webhook in conditional flow and revert RP dummy tests

---

ui-tests/src/test/resources/features/other/camelk.feature

//skip-ci 
Camel-k is no longer part of Fuse Online, so the tests fail.

Disable camel-k tests

---

operator-tests/src/test/java/io/syndesis/qe/OperatorValidationSteps.java
operator-tests/src/test/resources/features/check-metering-labels.feature

Now it checks the value of each metering label.

Backport to master - check that metering labels have correct values

---

utilities/src/main/java/io/syndesis/qe/resource/impl/Syndesis.java

//skip-ci
Added a wait for the fuse-operator to start, this caused fails when the bundle wasn't pulled to the cluster sometimes. And patching the CSV also failed sometimes when operator and the testsuite were changing it at the same time.

Fixed unstability for operatorhub install when bundle was not pulled
