syndesisio/syndesis-qe

- Jenkinsfile
WIP, do not merge, if the PR job fails.
> fix: use non-dsl arq variant in pipeline

- Jenkinsfile
> ci: Use released images by default

- e2e/integrations/datamapper.feature
Lets ignore currently undoable scenario for Atlasmap UI. Blocked by https://github.com/atlasmap/atlasmap/issues/28
> fix(atlasmap): Ignore advanced scenario until root cause is fixed

- package.json
> fix: Lock Chrome webdriver version to 2.30

- e2e/integrations/edit/datamapper.po.ts
Related to #1. It should increate stability during CI runs.
> fix(atlasmap): Increase wait timeout to prevent premature failure

- e2e/integrations/integration.steps.ts
> fix: Hiding navigation bar

- Jenkinsfile
It seems to work fine @dsimansk @iocanel
> [relates #12] Add ansi console excape

- Jenkinsfile
- README.md
- e2e/common/common.steps.ts
- e2e/common/common.ts
- e2e/common/world.ts
- e2e/connections/connections.feature
- e2e/connections/delete-connections.feature
- e2e/data/users.example.json
- e2e/integrations/datamapper.feature
- e2e/login/login.feature
- e2e/login/login.po.ts
still working progress, opening PR for discussion
> [relates #37] Load github user credentials from json settings

- Jenkinsfile
@jludvice wdyt too naive and simple?
> ci: Wait for the test namespace to be empty

- e2e/app.po.ts
- e2e/common/common.steps.ts
- e2e/connections/list/list.po.ts
- e2e/integrations/edit/edit.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/list/list.po.ts
it looks like navbar workaround is not needed anymore
test stability improvements
> Improve css selectors

- e2e/conf/protractor.base.conf.js
- e2e/connections/edit/edit.po.ts
- e2e/dashboard/dashboard.feature
- e2e/env.ts
- e2e/integrations/delete-integrations.feature
- e2e/integrations/integration.steps.ts
- e2e/integrations/multiple-steps-integrations.feature
- e2e/narratives/08-first-pass.feature
@dsimansk @lvydra  could you take a look if browser restart works fine for you please ?
> Browser restart after test feature

- e2e/dashboard/dashboard.feature
- e2e/integrations/delete-integrations.feature
- e2e/integrations/integration.steps.ts
- e2e/integrations/multiple-steps-integrations.feature
- e2e/narratives/08-first-pass.feature
[fix] Cover possibility of non present save button on integration edit
> [fix] Cover possibility of non present save button on integration edit

- e2e/integrations/datamapper.feature
Lets see if Jenkins is also happier with reordered flow.
> fix: Reorder connection create steps

- README.md
- e2e/app.po.ts
- e2e/connections/connections-kebab.feature
- e2e/connections/connections.steps.ts
- e2e/connections/list/list.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/integrations-kebab.feature
- e2e/integrations/list/list.po.ts
- e2e/integrations/utils/integrations.utils.ts
I repaired README.md. Without that,  step "Given clean application state" fails.
There is a difference how is kebab menu done in Integrations and Connections, 
that's why I couldn't do tests in one fashion.
it covers issues #548, #549, #550.
> [relates #19] Test for kebab menu functionality

- .gitignore
- README.md
- e2e/common/utils.ts
- e2e/integrations/edit/edit.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/twitter-search.feature
> [relates #03] Test for twitter search integration

- e2e/integrations/datamapper.feature
> fix(datamapper): Enable advanced scenario

- e2e/app.po.ts
- e2e/common/utils.ts
- e2e/connections/connections.steps.ts
- e2e/connections/list/list.po.ts
- e2e/integrations/edit/edit.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/integrations-kebab.feature
- e2e/integrations/list/list.po.ts
- e2e/integrations/multiple-steps-integrations.feature
- e2e/integrations/utils/integrations.utils.ts
> [relates #13] Basic filter test

- e2e/screenshots/screenshots.feature
- e2e/screenshots/screenshots.steps.ts
Screenshot directory is created under cucumber-reports directory.
> [fixes #42] Add scenario which creates screenshots at various resolutions

- Jenkinsfile
- README.md
- e2e/env.ts
> [improve] Add switch to restart browser between features

- e2e/app.po.ts
- e2e/common/common.steps.ts
- e2e/dashboard/dashboard.feature
- e2e/integrations/datamapper.feature
- e2e/integrations/delete-integrations.feature
- e2e/integrations/detail/detail.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/list/list.po.ts
- e2e/integrations/multiple-steps-integrations.feature
- e2e/integrations/twitter-search.feature
- e2e/narratives/08-first-pass.feature
Addition of integration detail page into create integration work flow
Refactor delete integration
> Integration detail page

- e2e/common/common.steps.ts
- e2e/connections/list/list.po.ts
- e2e/dashboard/dashboard.feature
- e2e/dashboard/dashboard.po.ts
- e2e/integrations/delete-integrations.feature
- e2e/integrations/integration.steps.ts
- e2e/integrations/list/list.po.ts
> [Fix] General changes on delete workflow

- e2e/app.po.ts
- e2e/integrations/basic-filter.feature
- e2e/integrations/edit/edit.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/multiple-steps-integrations.feature
> [relates #13] Basic Filter steps rule adding and deleting

- e2e/integrations/detail-page-integrations.feature
- e2e/integrations/detail/detail.po.ts
- e2e/integrations/integration.steps.ts
- e2e/integrations/list/list.po.ts
Check status methods
Status check on integration detail page
Checking status and actions on detail
> Delete on integration detail page

- Jenkinsfile
@lvydra fyi this enables demo data on fresh deployment.
> fix: Enable populating of demo data

- README.md
- e2e/app.po.ts
- e2e/conf/protractor.local.conf.js
- e2e/login/login.po.ts
- package.json
> [e2e-local] handle Minishift login page

- ui-tests-protractor/e2e/app.po.ts
- ui-tests-protractor/e2e/integrations/edit/edit.po.ts
- ui-tests-protractor/e2e/integrations/integration.steps.ts
Update of basic filter page object
> [fix] New input with drop down menu on basic filter

- ui-tests-protractor/e2e/app.po.ts
- ui-tests-protractor/e2e/login/login.po.ts
- ui-tests-protractor/package.json
Related to #85. The PR adds login to production cluster.
> chore(login): Add detection of prod cluster

- ui-tests-protractor/e2e/common/common.steps.ts
Wait for select element before start choosing desired option.
> [improve] Wait for select element

- ui-tests-protractor/e2e/integrations/edit/edit.po.ts
- ui-tests-protractor/e2e/integrations/twitter-to-salesforce-integration.feature
> [relates #65] Advanced filter step added to T2Sf scenario

- ui-tests-protractor/e2e/app.po.ts
@mcada fyi this should work with any browser :)
> fix(test-support): Execute reset-db in browser console

- ui-tests-protractor/e2e/app.po.ts
- ui-tests-protractor/e2e/common/common.steps.ts
- ui-tests-protractor/e2e/integrations/datamapper.steps.ts
- ui-tests-protractor/e2e/integrations/edit/datamapper.po.ts
- ui-tests-protractor/e2e/integrations/edit/edit.po.ts
- ui-tests-protractor/e2e/integrations/integration.steps.ts
- ui-tests-protractor/e2e/integrations/integrations-sf-db.feature
> [update] WIP implement Combine for Datamapper UI test

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListPage.java
Page objects for integrations list and some small refactoring on protractor integrations list page object side.
> Integration list page objects

- .gitignore
- ui-tests-protractor/e2e/common/utils.ts
- ui-tests-protractor/e2e/page-objects/app.po.ts
- ui-tests/src/test/java/io/syndesis/qe/common/World.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/ConnectionConfigurationComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/ConnectionCreatePage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/ConnectionDetailPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/ConnectionListPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/ConnectionsDetailsComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/ConnectionsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
pull request on refactoring - per partes
> [update] Work on e2e refactoring to Java

- ui-tests/src/test/java/io/syndesis/qe/pages/dashboard/DashboardPage.java
> [update] Work on e2e refactoring to Java - dashboard

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/detail/ConnectionDetailPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/edit/ConnectionConfigurationComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/edit/ConnectionCreatePage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/edit/ConnectionsDetailsComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/list/ConnectionListPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/list/ConnectionsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/detail/DataMapperComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
work on integrations/datamapper 
+ update of connections structure.
+ apply philosophy: wait for element (...shouldBe(...)) just immediately before element usage.
> [update] Work on e2e refactoring to Java - datamapper

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/detail/DataMapperComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/DataMapperSteps.java
> [update] Work on e2e refactoring to Java - datamapper-steps

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
I would let all unimplemented methods as they are until they are needed in a scenario.
I think those methods (like check integration title) should be implemented in the page objects they belong to. We can delete them once we are sure we don't need them or we don't need to track them anymore.
> [ui-tests] Common steps - several steps added

- rest-tests/src/test/java/io/syndesis/qe/rest/RestTestSuite.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/SalesforceDbTest.java
- rest-tests/src/test/resources/mappings/salesforce-db.json
- utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
- utilities/src/main/java/io/syndesis/qe/salesforce/Lead.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
There are still some unfinished things, will do it on Monday,  after we have all the new DB-related utils in the suite.
> [relates #103] Create SF-DB rest test

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/OAuthSettingsComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
> [update] Work on e2e refactoring to Java - settings-steps

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/FinishConnectionSelectComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationEditPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/StartConnectionSelectComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
> [fix] Integration steps minor fixes

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/steps/DataMapperComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/OAuthSettingsComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
> [closes #197] Exception handling update

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationConnectionSelectComponentStart.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationFlowViewComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationSaveOrAddStepComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations-sf-db.feature
correction of sf-to-db.feature
this is first step for fulfill task #38
> [relates #38] Datamapper separate feature

- ui-tests/src/test/resources/features/technical-extension.feature
> fix: One more tech ext fix

- pom.xml
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponentInvokeSql.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponentPeriodicSql.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponentSql.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ActionConfigureComponentTwitterSearch.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationEditPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationFlowViewComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/db-connection-step.feature
- ui-tests/src/test/resources/features/db-connection.feature
this is part1 + part2 amended into 1 commit.
after PR #221 is merged, I will rebase this branch, so please ignore part 1.
> [relates #114] DB Connector e2e tests. part 1+part2

- ui-tests/src/test/resources/features/db-connection-step.feature
- ui-tests/src/test/resources/features/db-connection.feature
> [relates #114] DB Connector e2e tests. part 3

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/TechnicalExtensionSteps.java
- ui-tests/src/test/resources/features/technical-extension.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/validation/TwSfValidationSteps.java
> refactor: Adapt to new Extension naming

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
- utilities/src/main/java/io/syndesis/qe/accounts/Account.java
- utilities/src/main/java/io/syndesis/qe/accounts/AccountsDirectory.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/validation/SfDbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/validation/TwSfValidationSteps.java
- utilities/src/main/resources/templates/syndesis-amq.yml
@Stefan365 this PR adds step to deploy AMQ broker and initializes Account also.
Usage:
```
Given deploy AMQ broker
And she fills "AMQ" connection details
```
> chore: Add AMQ template deployment

- docs/README.md
> [relates #194] Readme

- utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
@tplevko seems that my previous PR wasn't very successful. I tried to put a fallback together this time :)
> fix: More resilient local IP

- docs/README.md
> [relates #194] Readme. correction

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfDbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/TwSfValidationSteps.java
> chore(rest): moved validation steps to another package

- rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
On the way to enable parallel execution... Wdyt, be strict? :)
> chore: Add locking mechanism during test execution

- rest-tests/src/test/resources/features/integration-sf-db.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
@tplevko I've spotted some missing steps, pls review if I've figured it out or not :)
> fix(rest-tests): Fix missing steps in SF->DB

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
> [relates #281] DB verifying steps to scenarios. part 1

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/detail/IntegrationDetailPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationFlowViewComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
Remove all click methods from SyndesisPageObject. There should stay only getters. Having click methods there is a bit redundant.
> Remove click button methods

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- getModalDialog removed from SyndesisPageObject
- removed duplicate method clickModalButton from CommonSteps
> [ui-tests] Fix modal dialog button click step

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListComponent.java
- ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- ui-tests/src/test/resources/features/utils/debug-step.feature.example
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
> [relates #281] DB verifying steps to scenarios. part 2

- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
> [relates #281] DB verifying steps. correction

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationChooseStepComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationEditPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationStepSelectComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- ui-tests/src/test/resources/features/wip/db-connection-step.feature
- ui-tests/src/test/resources/features/wip/jms-connection.feature
This refactor is not complete, there are more parts that are worth to revise later for better orientation in the testsuite.
> [ui-tests] Refactor IntegrationSteps

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/DbSteps.java
- rest-tests/src/test/resources/features/integration-db-to-db-monitoring.feature
- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/mappings/db-db-monitoring.json
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
- ui-tests/src/test/resources/features/utils/debug-step.feature.example
- utilities/src/main/java/io/syndesis/qe/bdd/validation/MetricsValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/MetricsEndpoint.java
rest test prototype for metrics
> [relates #286] Rest metrics test

- .gitignore
- pom.xml
- ui-tests/pom.xml
- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
- ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/detail/IntegrationDetailPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/wip/integration-import-export.feature
Please look at these changes and lets discuss what should I change or if it is suitable for our purposes, there are still some TODOs which I have to figure out...
> Custom web driver provider set up, import/export integration test added, maven webdriver download plugin included

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/steps/BasicFilterStepComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/steps/StepComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/steps/StepComponentFactory.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
> Simple basic filter path data list verification 

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationBasicsComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationConnectionSelectComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationEditPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationFlowViewComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationStepSelectComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListPage.java
There was a change in root elements for integrations in master syndesis branch
> Integration pages root naming change

- ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java
- ui-tests/src/test/resources/features/wip/support-page.feature
WIP - tell me if you don't like what you see here so far :)
> Test for support page

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/ListActionsComponent.java
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- ui-tests/src/test/resources/features/other/support-page.feature
Another change happened in master branch and when selecting Twitter mention we now have to click on done button.
> Twitter mention is now correctly followed by click on done button step

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationSaveOrAddStepComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentPeriodicSql.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
> [update] Db to db ui tests update

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationFlowViewComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentPeriodicSql.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/steps/DataMapperComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- ui-tests/src/test/resources/features/wip/data-buckets.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
https://github.com/syndesisio/syndesis-qe/issues/288
For now it only tests popups. Next scenario will be on usage.
> Data buckets tests created

- README.md
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/FtpSteps.java
- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/RestConstants.java
ftp to ftp rest test, first shot.
> [relates #310] Ftp rest tests

- Jenkinsfile
- rest-tests/src/test/resources/features/integration-s3-to-s3.feature
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
If there is something which should stay with rest, comment it and I will reverse the change
> Syndesis-rest pod renamed to syndesis-server

- pom.xml
- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/FtpClientManager.java
- utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
FTP rest test, adding validation, part 1.
> [relates #310] Ftp rest, validation

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/IntegrationEditPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFieldFiller.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFtpDataType.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFtpDownload.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFtpUpload.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentJmsPublish.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentJmsRequest.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentJmsSubscribe.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
first shot for FTP UI e2e test
> [relates #310] Ftp ui test

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/DbSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/FtpSteps.java
- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- ui-tests/src/test/resources/features/wip/db-connection-step.feature
> [relates #310] Ftp rest, validation, correctios

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
- ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
> UI scenarios fixes

- utilities/src/main/resources/templates/syndesis-amq.yml
> [update] Amqp port addition

- pom.xml
- ui-tests/src/test/java/io/syndesis/qe/steps/other/DropBoxSteps.java
- ui-tests/src/test/resources/features/wip/dropbox-connection.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
https://github.com/syndesisio/syndesis-qe/issues/311
> Created test for dropbox connection

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFieldFiller.java
- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/FtpClientManager.java
@Stefan365 pls take look at TODO in `ActionConfigureComponentFieldFiller`
> Various fixes to FTP test

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/ImportIntegrationPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/detail/IntegrationDetailPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/list/IntegrationsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/java/io/syndesis/qe/utils/DragAndDropFile.java
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
https://github.com/syndesisio/syndesis-qe/issues/327
> Test for Integration import/export updated to reflect changes in UI

- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
I forgot to change this one status string after enabling all checks again
> Active state changed to Published state

- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFieldFiller.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFtpDataType.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFtpDownload.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/edit/actions/ActionConfigureComponentFtpUpload.java
- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
> [update] ActionConfigureComponentFieldFilter checkAndGet fix

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/ImportIntegrationPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/detail/IntegrationDetailPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/ExportedIntegrationJSONUtil.java
https://github.com/syndesisio/syndesis-qe/issues/368
> Test if connectors credentials are encrypted when exporting integration

- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- ui-tests/src/test/resources/features/integrations/database-to-database.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
How do we want to approach to database? As specific database methods are used over more modules it has to stay inside of utils module, should it stay in dbUtils or do we need yet another class with specific work with SQL queries?
> DbUtils refactor for simpler orientation and new implementation

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
//test: `@api-connector-integration`
> fix(ui): Handle multiple buttons with same text

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewEditConnectorDetails.java
> fix(ui): Fix create connector button

- ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
//test: `@integration-import-export`
> [ui][fix] Integration import scenarios squashed to one to avoid fails

- pom.xml
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/SlackSteps.java
- ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Resolves #441 
//test: `@slack`
> [ui][new] Adding test for slack connector

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/resources/features/customizations/extension-CRUD.feature
- ui-tests/src/test/resources/features/integrations/database-to-database-with-extension.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
//test: `@extension-CRUD-test`
> [ui][update] Update of extensions steps

- .circleci/config.yml
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/slack.feature
```
if (cciBuild.isSuccess()) {
avano.approve();
} else {
avano.spamAuthor();
}
```
> fix(circleci): Update browser deps

- ui-tests/src/test/java/io/syndesis/qe/pages/WizardPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewActions.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewEditConnectorDetails.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/wizard/WizardSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/invalid-swagger.feature
- ui-tests/src/test/resources/swagger/connectors/invalid/kie-server-swagger.json
//test: `@api-connector-invalid-swagger`
> [ui-tests] Api connector - invalid swagger test

- pom.xml
- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
- utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/DbWrapper.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
//test: `@integrations-db-to-db-mysql`
> [relates #445] Mysql

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/other/login-logout.feature
https://github.com/syndesisio/syndesis-qe/issues/450
//test: @logout-test
> [ui][new] Logout test

- README.md
- rest-tests/README.md
> [FUSEQE-1032] Add a note about GHPRB to Readme

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntermediateSteps.java
- rest-tests/src/test/resources/features/smoke.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
relates FUSEQE-1041
//test: @smoke
> [relates #1041] Rest smoke test

- ui-tests/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
solving #FUSEQE-1065,
waits after 'Given clean application state' 
untill PostgresDB connection has been created.
> [relates #1065] Postgres DB check solution 2

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/DropboxSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/FtpSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/S3Steps.java
- rest-tests/src/test/resources/features/file-transfer.feature
- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- rest-tests/src/test/resources/features/integration-s3-to-s3.feature
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DropBoxValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestConstants.java
- utilities/src/main/java/io/syndesis/qe/utils/S3BucketNameBuilder.java
File transfer test, see FUSEQE-1061. part 1 - separated integrations.
//test: @file-transfer
> [relates #1061] File transfer test

- pom.xml
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
- ui-tests/src/test/resources/features/integrations/gmail.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/GMailUtils.java
WIP as gmail connector in not yet fully implemented in syndesis but tests are done. Receive test fails, I will wait until they finish and merge oauth flow and if it still fails I will report new issue.
//test: @gmail
> [ui][new] Adding test for Gmail connector

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
//@edit-api-connector,@delete-api-connector
> Api connector fixes

- ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
Mysq test correction on jenkins server.
//test: @integrations-db-to-db-mysql
> [update] mysql test correction

- README.md
- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Please do not push sooner than on Monday 25 as I want nightly builds this week to run with longer delay.
> [ui][update] move test timeout from java to test.properties

- README.md
Update was based on current jenkins credentials which are used every day.
> [ui][update] Update readme to reflect new settings options required

- ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
> [ui][fix] Buttons renamed to reflect changes in syndesis-master

- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
> [Provision] Add some context when the integration is not provisioned

- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
> [Provision] Replace getPodWithPartialName

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHtmlRequest.java
- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
Just some basic schema for webhook test, UXD of webhook is not yet done so we are blocked for now.
//test: @webhook
> [ui][new] Webhook test

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui][new] Extending OAuth tests

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/other/login-logout.feature
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> [ui][update] updating logout test to reflect new logout endpoint

- pom.xml
- rest-tests/README.md
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/KafkaSteps.java
- rest-tests/src/test/resources/features/integration-kafka.feature
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- utilities/src/main/java/io/syndesis/qe/bdd/AbstractStep.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestConstants.java
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
> Add kafka test

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
> [ui][fix] fixing api client connector creating error

- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
//test: @integrations-salesforce-to-database
> [ui][enhancement] Smoothing database tests

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/HTTPSteps.java
- rest-tests/src/test/resources/features/integration-http-consumer.feature
- rest-tests/src/test/resources/features/integration-http-producer.feature
- rest-tests/src/test/resources/features/integration-kafka.feature
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/HTTPEndpointsTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestConstants.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> Fuseqe 1245 http

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
//test: @tech-extension-create-integration-with-new-tech-extension
> [ui][fix] delete modal dialog name change

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/importt/ImportIntegrationSteps.java
- ui-tests/src/test/java/io/syndesis/qe/utils/DragAndDropFile.java
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
//test: @integration-import-export
> [ui][fix] integration import-export fix

- ui-tests/src/test/resources/features/integrations/data-buckets.feature
> [ui][fix] Expand data bucket detail information

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/TelegramSteps.java
- ui-tests/src/test/resources/features/integrations/telegram.feature
- utilities/src/main/java/io/syndesis/qe/utils/TelegramUtils.java
> [ui][new] telegram semi-automated test

- ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
//test: @integrations-db-to-db-oracle12
> [ui][fix] Fixes for database tests

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/DbSteps.java
- rest-tests/src/test/resources/features/file-transfer.feature
- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- rest-tests/src/test/resources/features/integration-tw-sf.feature
- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DropBoxValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/FtpValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/S3ValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsActionsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/TestSupport.java
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/FtpTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/FtpClientManager.java
- utilities/src/main/java/io/syndesis/qe/utils/FtpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
> [FUSEQE-1425] Stabilize REST + cleanup

- rest-tests/src/test/resources/features/integration-tw-sf.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
> [FUSEQE-1425] Fix salesforce + retry login when unsuccessful

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> [FUSEQE-1502] Deploy syndesis via operator by default

- rest-tests/src/test/resources/features/integration-tw-sf.feature
> [rest][update] Use only one twitter credentials

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
//test: @syndesis-upgrade,@syndesis-upgrade-operator
> [FUSEQE-1454] Refactor upgrade + add operator upgrade

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/telegram.feature
//test: @oauth
Note that this will only work after PR with credentials update is merged.
> [ui][new] adding basic concur connectivity oauth test

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/menu/KebabMenu.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/ConnectionSteps.java
- ui-tests/src/test/resources/features/connections/connections.feature
- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
//test: @create-delete-api-connector
> [ui][fix] Stabilize smoke tests

- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
> [ui][fix] Stabilize webhook test

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/log-connector.feature
//test: @data-buckets-check-popups
> [ui][fix] Fix data buckets tests, add extension assert

- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
> [ui][fix] Update cucumber options to new format

- utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
- utilities/src/main/java/io/syndesis/qe/servicenow/model/Incident.java
- utilities/src/main/java/io/syndesis/qe/servicenow/model/IncidentRecordList.java
- utilities/src/main/java/io/syndesis/qe/servicenow/model/IncidentSingleResponse.java
- utilities/src/main/java/io/syndesis/qe/servicenow/model/LinkValue.java
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
> [FUSEQE-1585] Add basic service-now API wrapper

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/log-connector.feature
//test: @log-connector,@logout-test-logout
> [ui][fix] Fix log test, update log out test

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
> [ui][fix] Add dynamic wait when checking for existing extension

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> FUSEQE-1532

- utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
> [FUSEQE-1585] Add update incident

- pom.xml
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/ConnectionsGeneralSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationSteps.java
- rest-tests/src/test/resources/features/soak-deployment.feature
- rest-tests/src/test/resources/features/timer-connector.feature
- ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java
introduce general stesp for connection and integration step create
//test: @timer-connector
> [rest-test] Add timer connector tests

- ui-tests/src/test/resources/features/integrations/telegram.feature
> [ui][update] update telegram manual test steps

- README.md
> Update readme file - install syndesis from testsuite

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [Prod] Fail when prod repository is not set

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/resources/features/integrations/service-now.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/ServiceNowValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
add waiting for publish button
> [ServiceNow] add connector UI test

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/concur.feature
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
> [ui][new] adding basic concur test

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/concur.feature
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
> [ui][new] Adding new concur test

- rest-tests/src/test/java/io/syndesis/qe/CucumberTestsRunner.java
- rest-tests/src/test/resources/features/soak-deployment.feature
> [Ignore] Ignore tests with @ignore tag

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/AmqSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/JMSUtils.java
> [SF] Check for create responses

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
SlackConnector and Slack test was updated according to changed credentials.json.
Compatibility fix for 1.4.x.
//test: @slack-check-message-data-mapper
> [fix] SlackConnector and Slack test was updated

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- ui-tests/src/test/resources/features/integrations/service-now.feature
- ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
This should fix ~half of fails in nightly build :)
//test: @webhook
> [ui][fixes] Making tests more stable

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/resources/features/integrations/concur.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
> [ui][new] Extending concur tests

- README.md
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
https://issues.jboss.org/browse/FUSEQE-1955
> Add SAR_PROJECT argument for template deployments

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
> [ui][fix] fix api connector tests

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
//test: @data-buckets-check-popups
> [ui][fix] add dynamic wait for data mapper

- utilities/src/main/java/io/syndesis/qe/templates/MysqlTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
//test: @integrations-db-to-db-mysql
> [ui][fix] fix mysql timeout

- README.md
//skip-ci
@jstastny-cz thx for noticing, if you want to be proactive feel free to change the parsing and get rid of "@" symbol or create better logic ^^
> fix readme - how to run multiple scenarios via PR

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui][fix] do not fail the test when unknown oauth option is found

- README.md
> fix readme - how to update submodules

- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui][update] enable concur oauth connector test

- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Changes according to https://github.com/syndesisio/syndesis/issues/3586
//test: @slack-check-message-data-mapper
> [ui][fix] fix slack connection 

- README.md
- Fix create the project in OC
- Extract some tips to Most common problem subchapter
//skip-ci
> [README] update readme

- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
Changes according to https://github.com/syndesisio/syndesis/issues/3586
//test: @slack-check-message-data-mapper,@slack-to-db
> [ui][fix] fix slack connection

- README.md
> [README] - Add info about hotswap

- ui-tests/src/test/java/io/syndesis/qe/hooks/OnFailHooks.java
> [ui][disable] disable github afterhook due to ENG not liking our labels

- README.md
> [README] - add more information to Advanced debugging

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: @concur-listitem-create-delete
> [ui][fix] fix concur oauth validation

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/log-connector.feature
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
The test for https://github.com/syndesisio/syndesis/issues/3786 
//test: @log-connector-no-message
> Added test for GH - #3786

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
The test for https://github.com/syndesisio/syndesis/issues/3761 
//test: @slack-to-db-delay-and-maxmessage
> Added test for GH - #3761

- ui-tests/src/test/java/io/syndesis/qe/CustomWebDriverProvider.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
> [ui][fix] apicurito updated to new version

- ui-tests/pom.xml
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
- ui-tests/src/test/resources/jms_messages/tutorialAmqToRestMessage1.xml
- ui-tests/src/test/resources/jms_messages/tutorialAmqToRestMessage2.xml
- ui-tests/src/test/resources/jms_messages/tutorialAmqToRestMessage3.xml
- utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
tutorial integration AMQ to REST API (todo app)
contains extension and custom API (todo app) via URL
//test: @integrations-amq-to-rest
> [ui]add new integration test AMQ-REST API (todo app)

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/resources/kafka/strimzi-cluster-operator-0.8.2.yaml
- utilities/src/main/resources/kafka/strimzi-deployment.yaml
> [FUSEQE-2057] Use AMQ streams 1.0 for kafka testing

- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
> [FUSEQE-1717] Temporary comment out upgrade tests until refactor

- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/resources/features/other/3scale.feature
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
> [ui][new] 3scale discovery annotation test

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [Deploy] Don't fail when CRD already exists

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationOverviewEndpoint.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [FUSEQE-1717] Upgrade latest-1 to latest + create integration after

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> [CRD] Don't delete CRD when cleaning namespace

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
//skip-ci
probably not needed anymore, but just to have it right
> Operator 1.4.x

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [Operator] Fix for new operator deployment

- rest-tests/src/test/resources/features/integration-tw-sf.feature
- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
//test: @integrations-twitter-to-salesforce
> [fix] twitter to salesforce fix

- ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/Todo.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
- ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
- utilities/src/main/resources/templates/syndesis-amq.yml
Description: https://github.com/syndesisio/syndesis-qe/pull/625
//test: @integrations-amq-to-rest
> AMQ to REST NPE 1.5.x

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
> [Operator] Really use 1.5.x for operator for 1.5.x

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
> [Operator] Really use 1.4.x for operator for 1.4.x

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
> [Operator] Correctly use 1.5.x for deployments

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
> [Operator] Correctly use 1.4.x for deployments

- ui-tests/src/test/java/io/syndesis/qe/pages/apps/todo/Todo.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
- ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
- utilities/src/main/resources/templates/syndesis-amq.yml
Add sustainer tag
NPE was thrown when the AMQ instance exist but it doesn't have any pod. (e.g. after fresh FUSE ONLINE instalation)
//test: @integrations-amq-to-rest
> [fix] AMQ to REST NPE

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
> [Operator] Use syndesisVersion everywhere

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ChooseOperation.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ApiProviderWizard.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/NameApiProviderIntegration.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/UploadApiProviderSpecification.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
- ui-tests/src/test/resources/features/integrations/api-provider.feature
- ui-tests/src/test/resources/swagger/connectors/simple-string.json
- ui-tests/src/test/resources/swagger/connectors/todo.json
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
> [ui][new] API Provider tests

- README.md
- ui-tests/src/test/java/io/syndesis/qe/hooks/OnFailHooks.java
Please note that this change requires a new entry in credentials.json, see https://github.com/ZenHubIO/API#authentication how to obtain it.
> Introduce GitHub issue tag

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
- ui-tests/src/test/resources/features/other/settings-oauth.feature
//test: @oauth,@settings-oauth
> ui: added tests for OAuth Settings

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
> [ui][fix] fix data-buckets test

- README.md
- pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
the xtf bump should resolve issue from @asmigala that sometimes the waitForSyndesis ends too soon
//skip-ci
> [Operator] Undeploy syndesis before cleaning namespace

- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
//test: @integrations-db-to-db-oracle12
hopefully it will be enough to fix that :dancer:
> [FUSEQE-2430] Fix oracle12 test

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
//test: @syndesis-upgrade,@syndesis-upgrade-operator
> [FUSEQE-2542] Fix upgrade using operator

- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
> [ui][update] add dynamic wait in 3scale test for syndesis-server restart

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/integration-status.feature
- ui-tests/src/test/resources/features/integrations/log-connector.feature
- ui-tests/src/test/resources/features/integrations/mqtt.feature
- ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
add enable-test-support scenario for running on stagings
//test: @stage-smoke
> fix loging on stagings

- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
> [FUSEQE-2430] Fix oracle12 1.5

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
> [ui][update] dynamic wait for connections selection

- pom.xml
- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/TelegramSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/HTTPResponse.java
- utilities/src/main/java/io/syndesis/qe/utils/HttpUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/TelegramUtils.java
//test: @smoke,@upgrade,@rollback,@syndesis-upgrade-operator,@smoke
> [Upgrade] Tweak clearing upgrade properties

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> [FUSEQE-2601] Increase provision timeout

- rest-tests/src/test/resources/features/integration-tw-sf.feature
- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
> [fix] twitter to salesforce fix + typo correction

- README.md
- ui-tests/src/test/java/io/syndesis/qe/hooks/OnFailHooks.java
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
- ui-tests/src/test/resources/features/integrations/api-provider.feature
> 1.5.x GitHub tags

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@db-connection-crud-1-read-update`
> [ui][update] dynamic wait for navigation and connector action selection

- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
//test: `@ftp-download-ftp-upload`
> [ui][fix] fix @ftp-download-ftp-upload test

- README.md
- pom.xml
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/HTTPSteps.java
- rest-tests/src/test/resources/features/file-transfer.feature
- rest-tests/src/test/resources/features/integration-ftp-to-ftp.feature
- rest-tests/src/test/resources/features/integration-http-consumer.feature
- rest-tests/src/test/resources/features/integration-http-producer.feature
- rest-tests/src/test/resources/features/integration-kafka.feature
- rest-tests/src/test/resources/features/integration-monitoring.feature
- rest-tests/src/test/resources/features/integration-s3-to-s3.feature
- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- rest-tests/src/test/resources/features/integration-tw-sf.feature
- rest-tests/src/test/resources/features/smoke.feature
- rest-tests/src/test/resources/features/timer-connector.feature
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/JmsValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/AtlasmapEndpoint.java
- utilities/src/main/java/io/syndesis/qe/wait/OpenShiftWaitUtils.java
> [FUSEQE-2624] Map HTTP connector output

- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@3scale,@logout-test-logout-login`
> [ui][update] remove static wait from 3scale afterhook

- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
> [ui][new-test] added webhook integration tests

- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> Update error message when Syndesis is not in the namespace

- README.md
- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
Rewrite default timeout for selenide collections, decrease default timeout to 30s
> [ui][new] rewrite default timeout for selenide collection operations

- pom.xml
> [ActiveMQ] Bump ActiveMQ version

- ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TodoUtils.java
just a test if it helps, if not I'll reset it afterwards :-)
> [FUSEQE-2825] Create todo2 route after deploying syndesis

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
- ui-tests/src/test/resources/features/other/integration-metrics.feature
* Test for Start Date was added
* Test for Uptime was added
//test: `@integration-metrics`
> Extend Metrics test about testing uptime and start date

- ui-tests/src/test/resources/features/integrations/data-buckets.feature
//test: `@integrations-data-buckets`
> [ui-tests] Fix data-bucket tests

- ui-tests/src/test/resources/features/integrations/ftp-to-ftp.feature
- ui-tests/src/test/resources/features/integrations/gmail.feature
- ui-tests/src/test/resources/features/integrations/google-calendar.feature
- ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
- ui-tests/src/test/resources/features/other/3scale.feature
//test: `@integrations-ftp-to-ftp,@integrations-gmail,@slack,@integrations-twitter-to-db,@3scale`
> [FUSEQE-2893] Fix UI tests after UI changes

- ui-tests/pom.xml
- ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
Test for db-2-db quickstart: https://github.com/syndesisio/syndesis-quickstarts/tree/master/db-2-db
//test: `@quickstart-db-2-db`
> Create db-2-db quckstart test

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
Signed-off-by: mmajerni <mmajerni@redhat.com>
//test: `@apicurio`
> [UI-tests]Fix apicurio tests

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/RowList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisRootPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/WizardPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/SelectConnectionType.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/wizard/ReviewApiProviderActions.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/NameConnectionSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/MonitoringValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/ExtensionsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsMetricsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/utils/GoogleAccount.java
Removes imports that are not used from the codebase also prevents my eye from twitching.
> chore: remove unused imports

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
> [Upgrade] Use scripts from minorVersion during daily upgrade

- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
> [GH-4308] Temporary disable all tests with extensions

- README.md
//test: `(@rest and @integrations-amq-irc) or (@ui and @log-connector-error-message)`
> [README] Update PR test notation

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [Operator] Revert back to pre-SSO operator deployment

- rest-tests/src/test/resources/features/integration-tw-sf.feature
- rest-tests/src/test/resources/features/smoke.feature
//test: `'@integrations-tw-sf'`
> [REST] Fix Twitter to Salesforce ids

- rest-tests/src/test/resources/features/upgrade-prod.feature
- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/resources.yml
> [FUSEQE-2976] Automate prod upgrade procedure

- ui-tests/src/test/resources/features/integrations/concur.feature
> [ui][fix] fix concur scenario

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
//test: `'@upgrade or @syndesis-upgrade-operator'`
> [FUSEQE-3045] Temporary edit upgrade tests

- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
//test: `'@salesforce and @rest'`
> Rest fixes

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/ChooseAction.java
//test: `@db-connection-crud-1-read-update`
> [ui][fix] fix data mapper card and action selection

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/dropbox-to-dropbox.feature
- ui-tests/src/test/resources/features/integrations/gmail.feature
- ui-tests/src/test/resources/features/integrations/google-calendar.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
- ui-tests/src/test/resources/features/integrations/log-connector.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- ui-tests/src/test/resources/features/integrations/telegram.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
- ui-tests/src/test/resources/features/other/support-page.feature
> [ui][fix] change save button name

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
//test: `@db-connection-crud-1-read-update`
> [ui][fix] fix data mapper collection mappings

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> Fix enabling test support

- utilities/src/main/java/io/syndesis/qe/templates/HTTPEndpointsTemplate.java
> [HTTPEndpoints] Add wait for HTTP endpoints

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [FUSEQE-3209] Fix new plural form of syndesis resource

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [Deploy] Avoid infinite loop while waiting for image streams

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/SplitSteps.java
- rest-tests/src/test/resources/features/integration-monitoring.feature
- rest-tests/src/test/resources/features/smoke.feature
- rest-tests/src/test/resources/features/upgrade-prod.feature
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- utilities/src/main/java/io/syndesis/qe/bdd/AbstractStep.java
- utilities/src/main/java/io/syndesis/qe/endpoints/AbstractEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/StepDescriptorEndpoint.java
> Fuseqe 3109 split aggregate

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
- ui-tests/src/test/resources/features/other/integration-activity.feature
//test: `@activity and not @gh-4192`
> Update activity test according to gh-4407

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> [Undeploy] Remove all syndesis CRDs during undeployment

- ui-tests/src/test/resources/features/integrations/sql-connector.feature
> created SQL connector reproducer test for gh-3856

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
> [ui][fix] fix support page tests to reflect UI update

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
This reverts commit 775969a0a0bc16f4e1085e842e31f22b2ab18f0a.
//skip-ci
> Revert "[Undeploy] Remove all syndesis CRDs during undeployment"

- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
> [FUSEQE-3209] Revert plural syndesis form

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationHandler.java
> [FUSEQE-3285] Add tags to the integrations created in REST suite

- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/concur.feature
- ui-tests/src/test/resources/features/integrations/integration-status.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
> [ui][fix][FUSEQE-3282] make scenario names unique

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/vars
> [FUSEQE-2976] Prod upgrade - add file that exports the variables

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> [install] increase timeout when cleaning syndesis namespace

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
> [FUSEQE-3321] Switch branches when doing upgrade

- rest-tests/src/test/resources/features/upgrade-prod.feature
- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/resources.yml
- rest-tests/src/test/resources/upgrade/prod/vars
> Fuseqe 3321 1.5.x

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/IntegrationSteps.java
- rest-tests/src/test/resources/features/upgrade-prod.feature
- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/resources.yml
- rest-tests/src/test/resources/upgrade/prod/vars
- utilities/src/main/java/io/syndesis/qe/bdd/validation/HTTPValidationSteps.java
> Fuseqe 3321 1.4.x

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
- ui-tests/src/test/resources/features/other/integration-activity.feature
- ui-tests/src/test/resources/features/other/integration-metrics.feature
//test: `@activity and @metrics and not @gh-4192`
> [ui][update] Update activity/metrics (reproducer for gh-4162)

- ui-tests/src/test/resources/features/integrations/service-now.feature
> [service-now] fix tests by changing ids

- pom.xml
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleSheetsSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
- ui-tests/src/test/resources/features/integrations/google-sheets.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleSheetsValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/GoogleAccount.java
- utilities/src/main/java/io/syndesis/qe/utils/GoogleAccounts.java
- utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java
> [google-sheets] add google sheets connector tests

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
> [ui][fix] fix logout tests to reflect UI changes

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> [FUSEQE-3430] Print pods when something bad happens

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- ui-tests/pom.xml
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
> Fuseqe 3398 refactor upgrade

- pom.xml
> [POM] Bump syndesis version

- pom.xml
> [FUSEQE-3493] Bump postgresql version

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IntegrationSteps.java
- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
> [FUSEQE-3330] Rebuild integration after upgrade 1.6.x

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/IntegrationSteps.java
- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
> [FUSEQE-3330] Rebuild integration after upgrade

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> [Upgrade] Fix floating point issues + deploy using operator 1.6

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> Upgrade split

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui][update] OAuth tests now validate every connector with OAuth 1.6.x

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui][update] OAuth tests now validate every connector with OAuth

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> [Undeploy] Don't fail when can't parse json response

- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
> Undeploy syndesis 1.6

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
//test: `@apicurio-check-operations-change-add`
> [ui][fix] fix apicurio tests 16x

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
//test: `@apicurio-check-operations-change-add`
> [ui][fix] fix apicurio tests

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
//test: `@db-connection-crud-2-read-create`
> [ui][fix] navigate to integrations page when validating integration status 16x

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
//test: `@db-connection-crud-2-read-create`
> [ui][fix] navigate to integrations page when validating integration status

- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/concur.feature
> [ui][disable] disable concur tests 16x

- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/concur.feature
> [ui][disable] disable concur tests

- template/prod.template.yml
> Fuseqe 3537 prod template 1.6

- rest-tests/src/test/resources/features/file-transfer.feature
- rest-tests/src/test/resources/features/integration-monitoring.feature
- rest-tests/src/test/resources/features/integration-s3-to-s3.feature
- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/integration-tw-sf.feature
- rest-tests/src/test/resources/features/irc.feature
- utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
> Fix dropbox

- utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
> Fix dropbox 1.6

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@integrations-amq-to-rest`
> AMQ to REST jenkins fix

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
//test: `@apicurio-check-operations-change-remove`
> [ui][fix] fix apicurio operation remove test 16x

- ui-tests/src/test/java/io/syndesis/qe/steps/other/KuduSteps.java
- ui-tests/src/test/resources/features/integrations/kudu.feature
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/MqttValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/KuduTemplate.java
- utilities/src/main/resources/templates/syndesis-kudu.yml
> [ui][new] kudu connector test 16x

- ui-tests/src/test/java/io/syndesis/qe/steps/other/KuduSteps.java
- ui-tests/src/test/resources/features/integrations/kudu.feature
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/MqttValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/KuduRestAPITemplate.java
- utilities/src/main/java/io/syndesis/qe/templates/KuduTemplate.java
- utilities/src/main/resources/templates/syndesis-kudu.yml
> [ui][new] kudu connector test

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- template/generate.sh
- template/vars
> [FUSEQE-3527] Unify bash scripts approach

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
//test: `@apicurio-check-operations-change-remove`
> [ui][fix] fix apicurio operation remove test

- ui-tests/src/test/resources/features/integrations/db-to-db.feature
//test: `@integrations-db-to-db`
> Fix DB to DB tests - add split step

- ui-tests/src/test/resources/features/integrations/db-to-db.feature
- ui-tests/src/test/resources/features/integrations/gmail.feature
> Fix gmail tests split

- ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
//test: @split-aggregate-flow-1
> Add split/aggregate tests

- ui-tests/src/test/resources/features/integrations/concur.feature
- ui-tests/src/test/resources/features/integrations/sql-connector.feature
- ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
//test: `@sql-connector-all-rows`
> [ui][fix] swap simple logger for just log connector

- ui-tests/src/test/resources/features/integrations/concur.feature
- ui-tests/src/test/resources/features/integrations/sql-connector.feature
- ui-tests/src/test/resources/features/soak-deployments/SimpleSoakTestDeployment.feature
//test: `@sql-connector-all-rows`
> [ui][fix] swap simple logger for just log connector 16x

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/log-connector.feature
> [ui][new] extend log connector tests

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/log-connector.feature
> [ui][new] extend log connector tests 17x

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
> [Upgrade] Skip upgrade tests with prod version

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> Refactor binary client

- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/integration-sf-producers.feature
- rest-tests/src/test/resources/features/irc.feature
> [FUSEQE-3679] Remove chars that cause problems when parsing

- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
> [ui][fix] fix webhook test

- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
> [ui][fix] fix webhook test 16x

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
//test: `@data-buckets-check-popups`
> [ui][fix] fix dataBucket tests

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
//test: `@data-buckets-check-popups`
> [ui][fix] fix dataBucket tests 16x

- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
> [ui][fix] tw to sf test fix 1.6.x

- ui-tests/src/test/resources/features/integrations/slack.feature
> [ui][fix] fix slack tests 16x

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/extensions/TechExtensionsListComponent.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
//test: `@tech-extension-create-integration-with-new-tech-extension`
> fix @tech-extension-create-integration-with-new-tech-extension

- ui-tests/src/test/resources/features/other/3scale.feature
> [ui][fix] fix 3scale tests 16x

- utilities/src/main/java/io/syndesis/qe/templates/SyndesisTemplate.java
> [Template] Fix image stream count when using template

- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
Added split steps before DB connections
ping @mastepan so we don't all fix the same tests
> fix api-client-connector

- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/db-to-db.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/integration-status.feature
- ui-tests/src/test/resources/features/integrations/kudu.feature
- ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
- ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
> [ui][fix] open data mapper collections before mapping starts

- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/db-to-db.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/integration-status.feature
- ui-tests/src/test/resources/features/integrations/kudu.feature
- ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
- ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
> [ui][fix] open data mapper collections before mapping starts 16x

- ui-tests/src/test/resources/features/integrations/slack.feature
> [ui][fix] fix slack tests

- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
> [ui][fix] tw to sf test fix

- template/generate.sh
- template/prod.template.yml
- template/vars
> [Generator] Fix for current version

- ui-tests/src/test/resources/features/other/3scale.feature
> [ui][fix] fix 3scale tests

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/import-edit.feature
//test: `@import-edit-integration`
> [ui][fix] fix import edit test

- utilities/src/main/java/io/syndesis/qe/templates/AmqTemplate.java
> [AMQ] Remove service created by operator if present

- README.md
- docs/generateDocs.py
> [doc] added script to generate list of step definitions

- rest-tests/src/test/resources/features/integration-sf-producers.feature
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
//test: `@integration-sf-producers-delete-record or @integration-sf-producers-delete-record-external-id or @integration-sf-producers-fetch-record or @integration-sf-producers-fetch-record-external-id`
> [FUSEQE-3680] Fix failing salesforce tests

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/sql-connector.feature
> [ui][sql] Add tests for SQL predicates (gh-5016)

- ui-tests/src/test/resources/features/integrations/sql-connector.feature
> [ui][sql] Copypasta to have clean test report

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/sql-connector.feature
> [ui][sql] Add tests for SQL predicates - master

- .github/PULL_REQUEST_TEMPLATE.md
> [GitHub] Add PR template

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/resources.yml
- rest-tests/src/test/resources/upgrade/prod/vars
> [FUSEQE-3678] Add INFRA_ONLY + some changes for jenkins

- ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleCalendarSteps.java
- ui-tests/src/test/resources/features/integrations/google-calendar.feature
- utilities/src/main/java/io/syndesis/qe/bdd/utils/GoogleCalendarSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleCalendarValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/GoogleCalendarUtils.java
Google Calendar tests now add a random suffix to the calendar name to
prevent collisions between concurrent tests
//test: `@google-calendar`
> [ui][google-calendar] Use aliased calendar name 1.6.x

- ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleCalendarSteps.java
- ui-tests/src/test/resources/features/integrations/google-calendar.feature
- utilities/src/main/java/io/syndesis/qe/bdd/utils/GoogleCalendarSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/GoogleCalendarValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/GoogleCalendarUtils.java
Google Calendar tests now add a random suffix to the calendar name to
prevent collisions between concurrent tests
//test: `@google-calendar`
> [ui][google-calendar] Use aliased calendar name

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/resources.yml
- rest-tests/src/test/resources/upgrade/prod/vars
> Fuseqe 3678 prod upgrade 1.6.x

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
//test: `@create-delete-api-connector`
> Fix @create delete api connector

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
//test: `@integrations-data-buckets`
> [ui][update] update data buckets tests

- rest-tests/src/test/resources/features/upgrade-prod.feature
> [FUSEQE-3330] Rebuild integration after prod upgrade

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/resources/features/other/3scale.feature
> [ui][fix] stabilize 3scale annotation test

- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
//test: `@integration-import-export-classic-and-dnd`
> [ui][fix] fix integration import-export scenarios

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
//test: `@create-delete-api-connector`
> [ui][fix] stabilize api connector test

- pom.xml
//test: `@integration-http-producer-get`
> [POM] Bump activemq version

- ui-tests/pom.xml
- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/ApiProviderOperationEditorPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/ChooseStep.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/apiprovider/ApiProviderToolbar.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/api-provider.feature
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
Depends on Apicurio/apicurio-qe#5 and ci-ops-fuse MR #428
//test: `@api-provider-create-from-spec`
> [api-provider] Fix failing tests and introduce new ones 1.6.x

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/IntegrationHandler.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/DataMapperSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/IntermediateSteps.java
- rest-tests/src/test/resources/features/integration-aggregate.feature
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
- utilities/src/main/java/io/syndesis/qe/bdd/entities/DataMapperDefinition.java
- utilities/src/main/java/io/syndesis/qe/bdd/entities/DataMapperStepDefinition.java
//test: `@rest and @datamapper`
> [FUSEQE-3217] rest aggregate

- pom.xml
- rest-tests/pom.xml
- ui-tests/pom.xml
- utilities/pom.xml
> [POM] Fix maven clashes

- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/AddToIntegration.java
> [ui][fix] Fix my blunder of renaming AddToIntegration

- ui-tests/src/test/java/io/syndesis/qe/CucumberTest.java
These are included as part of the test-jar, but should not be run
//skip-ci
> [ui] Skip apicurito standalone tests

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/database/InvokeSql.java
- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
- ui-tests/src/test/resources/features/integrations/webhook-db.feature
//test: `@integrations-webhook-db`
> [ui] - reproducer for #gh-4182

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
fix for UI
//test: `@integration-metrics`
> [UI][fix] - test fix for gh-5100

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/integration-status.feature
- ui-tests/src/test/resources/features/integrations/log-connector.feature
- ui-tests/src/test/resources/features/integrations/mqtt.feature
- ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
> add stage smoke to 1.6.x branch

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/integration-status.feature
- ui-tests/src/test/resources/features/integrations/log-connector.feature
- ui-tests/src/test/resources/features/integrations/mqtt.feature
- ui-tests/src/test/resources/features/integrations/openwire-to-openwire.feature
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/OpenShiftUtils.java
> add  stage-smoke to master

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/resources/features/integrations/google-sheets.feature
- ui-tests/src/test/resources/features/integrations/service-now.feature
- utilities/src/main/java/io/syndesis/qe/utils/GoogleSheetsUtils.java
add  SS->DB->SS scenario
refactor google sheet utils to connect create only when necessary
attempt to fix servicenow test
//test `@google-sheets`
> [google-sheets] fix tests

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui] Tests for OAuth connectors

- README.md
- hooks/pre-push
> [Hooks] Add pre-push hook

- rest-tests/src/test/resources/features/upgrade-syndesis.feature
> [Rollback] Add gh issue annotation

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
> [Upgrade] Don't manually modify s2i tag

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/connection/ConnectionActionSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
- ui-tests/src/test/resources/features/integrations/kudu.feature
//test: `@support-page-download-specific-diagnostic or @data-buckets-usage-2`
> [ui][fix] stabilize support page and data buckets tests

- ui-tests/src/test/resources/features/integrations/google-sheets.feature
> [google-sheets] fix test failing due to added new page in connector

- ui-tests/src/test/resources/features/integrations/google-calendar.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
//test: `@google-calendar-get-event`
> [ui][fix] Fix Google Calendar get event test

- rest-tests/src/test/resources/features/integration-http-producer.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
//test: `@integration-http-sql-split`
> [FUSEQE-3726] Add reproducer for GH-5093

- pom.xml
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
- rest-tests/src/test/resources/features/integration-box.feature
- utilities/pom.xml
- utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
> [FUSEQE-3823] Add box connector tests

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/resources/features/check-prod-versions.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/ProdValidationSteps.java
> [FUSEQE-3845] Add check for prod build integrations

- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/smoke.feature
- ui-tests/src/test/resources/features/integrations/api-provider.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/db-to-db.feature
- ui-tests/src/test/resources/features/integrations/import-edit.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
//test: `@slack or @integration-sf-db-delete or @import-edit-integration`
> [ui, rest][refactor] refactor database validation steps

- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
//test: `@db-connection-crud-1-read-update`
> [ui][fix] fail the validation step when result set thorws an exception

- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/smoke.feature
- ui-tests/src/test/resources/features/integrations/api-provider.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/db-to-db.feature
- ui-tests/src/test/resources/features/integrations/import-edit.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
//test: `@slack or @integration-sf-db-delete or @import-edit-integration`
> [ui, rest][refactor] update database validation steps

- rest-tests/src/test/java/io/syndesis/qe/upgrade/UpgradeSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/KafkaTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> [Upgrade] Fix missing file copy

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/accounts/Account.java
- utilities/src/main/java/io/syndesis/qe/accounts/AccountsDirectory.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/hooks/IssueHooks.java
- utilities/src/main/java/io/syndesis/qe/servicenow/ServiceNow.java
- utilities/src/main/java/io/syndesis/qe/utils/BoxUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/DropBoxUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
- utilities/src/main/java/io/syndesis/qe/utils/SlackConnector.java
- utilities/src/main/java/io/syndesis/qe/utils/TelegramUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/mqtt/MqttUtils.java
> [Accounts] Use enum for account names

- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
> [DB] Slight refactor of DB things

- utilities/src/main/java/io/syndesis/qe/accounts/AccountsDirectory.java
> [Account] Fix getting the account using the enum

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/EnvironmentsPublicApiSteps.java
- utilities/src/main/java/io/syndesis/qe/TestConfiguration.java
- utilities/src/main/java/io/syndesis/qe/bdd/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/ConnectionsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/EnvironmentsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/PublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/RestUtils.java
//skip-ci
Created template and service account for PublicApi
Created endpoints for PublicApi
> PublicApi oauth Template, service account, endpoints for Public API

- rest-tests/src/test/resources/features/integration-http-producer.feature
//test: `@integration-http-sql-split`
> [HTTP] Fix step name after refactoring

- utilities/src/main/java/io/syndesis/qe/cucumber/MailFormatter.java
> Mark skipped tests in mail report

- README.md
> [README] Fix for syntax

- ui-tests/src/test/java/io/syndesis/qe/steps/other/ODataSteps.java
- ui-tests/src/test/resources/features/integrations/odata.feature
- utilities/src/main/java/io/syndesis/qe/TestSuiteParent.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/OpenshiftValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/templates/WildFlyTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/ODataUtils.java
- utilities/src/main/resources/templates/syndesis-wildfly.yml
> odata connector smoke and reproducer tests

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
> [Connections] Refactor creating connections

- README.md
- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/ConnectionsPublicApiSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/EnvironmentsPublicApiSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/IntegrationsPublicApiSteps.java
- rest-tests/src/test/resources/features/publicapi/connections.feature
- rest-tests/src/test/resources/features/publicapi/environments.feature
- rest-tests/src/test/resources/features/publicapi/integrations.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/Verifier.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/EnvironmentsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> REST tests for PublicAPI and export/import

- README.md
- pom.xml
- ui-tests/pom.xml
> [ui][new] allow to set webdriver version from maven command to support older browsers

- README.md
- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/ConnectionsPublicApiSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/EnvironmentsPublicApiSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/IntegrationsPublicApiSteps.java
- rest-tests/src/test/resources/features/publicapi/connections.feature
- rest-tests/src/test/resources/features/publicapi/environments.feature
- rest-tests/src/test/resources/features/publicapi/integrations.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/CommonValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/IntegrationsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/Verifier.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/EnvironmentsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/IntegrationsPublicEndpoint.java
- utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/TestUtils.java
> [Backport master] REST tests for PublicAPI and export/import

- ui-tests/src/test/resources/features/integrations/api-provider.feature
> Add annotations for tests affected by gh-5332

- ui-tests/src/test/resources/features/integrations/api-provider.feature
- ui-tests/src/test/resources/swagger/connectors/collection.json
//test: `@api-provider-post-collection`
> [FUSEQE-4416] Fix @api-provider-post-collection

- ui-tests/src/test/resources/features/quickstarts/db-to-db.feature
- ui-tests/src/test/resources/features/quickstarts/hello-world.feature
> [ui][fix] fix ambiguous button titles

- ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
//test: `@split-aggregate-flow-1`
> [ui][fix] fix split-aggregate flow

- README.md
- pom.xml
- ui-tests/pom.xml
> Browsers 1.6.x

- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
> [ui][tags] add github issue tags for apicurio security bug

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/email.feature
- ui-tests/src/test/resources/features/integrations/gmail.feature
- ui-tests/src/test/resources/features/integrations/template.feature
This tests basic functionality of both email connectors - send and receive
//test: `@email`
> [FUSEQE-4209] gherkin scenario for email connectors

- rest-tests/src/test/resources/features/integration-tw-sf.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SfValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/SalesforceAccount.java
> [refactor] refactor salesforce validation steps

- rest-tests/src/test/resources/features/integration-monitoring.feature
- rest-tests/src/test/resources/features/integration-sf-db.feature
- rest-tests/src/test/resources/features/smoke.feature
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
//test: `@rest and @database and @datamapper and not @sqs`
> [DB] Refactor to DB collection in datamapper

- rest-tests/src/test/resources/features/upgrade-syndesis-operator.feature
- rest-tests/src/test/resources/features/upgrade-syndesis.feature
> [Upgrade] Temporary ignore upgrade tests

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/connection/Connections.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/util/RestTestsUtils.java
- rest-tests/src/test/resources/features/integration-sns.feature
- rest-tests/src/test/resources/features/integration-sqs.feature
- rest-tests/src/test/resources/features/smoke.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SNSValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/SQSValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/SNSUtils.java
- utilities/src/main/java/io/syndesis/qe/utils/SQSUtils.java
> [FUSEQE-4294] Add SNS test

- ui-tests/src/test/resources/features/integrations/email.feature
- ui-tests/src/test/resources/features/integrations/gmail.feature
This adds testing of a new feature of email connector (starttls support) as long as pop3 protocol.
//test: `@email`
> [FUSEQE-4426] updated scenario to test starttls (smtp) and pop3 for email connector

- checkstyle/checkstyle.xml
- hooks/prepare-commit-msg
> [checkstyle] Tweak checkstyle, prevent bypassing by not staging

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/integrations/steps/ConnectionSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/S3Utils.java
> [S3] Change account name to AWS

- checkstyle/checkstyle.xml
> [Checkstyle] Add rules for static imports

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/sql-connector.feature
//test: `@sql-connector-return-keys`
> Reproducer for gh-4466: SQL connector should return generated keys

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/steps/flow/ConnectionSteps.java
- rest-tests/src/test/resources/features/integration-database.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/DbValidationSteps.java
- utilities/src/main/java/io/syndesis/qe/endpoints/ConnectionsActionsEndpoint.java
- utilities/src/main/java/io/syndesis/qe/utils/DbUtils.java
//test: `@integrations-db-stored-procedures`
> [FUSEQE-4099] Add DB stored procedures test

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- template/generate.sh
> [Exporter] Use tech preview namespace for exporter

- rest-tests/src/test/resources/upgrade/prod/prod-upgrade.sh
- rest-tests/src/test/resources/upgrade/prod/vars
> [Upgrade] Use pull secret

- ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
- ui-tests/src/test/resources/features/connections/connections.feature
> [Connection tests] fix buttons in connection tests

- ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java
- ui-tests/src/test/resources/features/other/support-page.feature
> [ui][fix] support page feature

- ui-tests/src/test/resources/features/connections/connections.feature
- ui-tests/src/test/resources/features/integrations/service-now.feature
> Fix servicenow tests

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-mysql.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-oracle12.feature
- ui-tests/src/test/resources/features/integrations/db-to-db.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
> [ui][fix] get rid of failing old mapping step

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
- ui-tests/src/test/resources/features/integrations/kudu.feature
> [ui][fix] fix kudu feature

- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/api-provider.feature
- ui-tests/src/test/resources/features/integrations/concur.feature
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/email.feature
- ui-tests/src/test/resources/features/integrations/gmail.feature
- ui-tests/src/test/resources/features/integrations/google-calendar.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
- ui-tests/src/test/resources/features/integrations/integration-import-export_backup.feature
- ui-tests/src/test/resources/features/integrations/kudu.feature
- ui-tests/src/test/resources/features/integrations/slack.feature
- ui-tests/src/test/resources/features/integrations/telegram.feature
- ui-tests/src/test/resources/features/integrations/template.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
- ui-tests/src/test/resources/features/other/support-page.feature
> [ui][fix] change integration save from button to link

- ui-tests/src/test/resources/features/integrations/gmail.feature
gmail integration fixes for the new UI
//skip-ci
> [UI] fix the gmail integration feature with new ui

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/other/3scale.feature
> [ui][fix] fix 3scale feature

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/pages/SyndesisPageObject.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
- ui-tests/src/test/resources/features/integrations/webhook-db.feature
- ui-tests/src/test/resources/features/other/integration-activity.feature
- ui-tests/src/test/resources/features/other/integration-metrics.feature
* the url for webhook is taken from OpenShift instead of UI
//skip-ci
> [UI][fix] - update Webhook tests

- ui-tests/src/test/resources/features/integrations/sql-connector.feature
> sql connector tests react ui fix

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/integrations/kudu.feature
> [ui][fix] fix the rest of the kudu scenarios

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [fixaton] changed oauth tests for react

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/AbstractUiElementsList.java
- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/CardList.java
- ui-tests/src/test/java/io/syndesis/qe/fragments/common/list/actions/ListAction.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/fragments/list/ConnectionsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/Integrations.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/database/PeriodicSql.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/OperationsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apiprovider/ApiProviderSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
- ui-tests/src/test/resources/features/integrations/import-edit.feature
- ui-tests/src/test/resources/features/integrations/split-aggregate-steps.feature
//skip-ci
updated tests: 
integrations-db-to-db-with-extension
import-edit-integration
split-aggregate
> [fix] changed several tests to react

- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
- ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
> [ui][fix] fix customization page navigation

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/ReviewActions.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/UploadSwaggerSpecification.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/invalid-swagger.feature
//test: `@check-invalid-swagger-messages`
> [ui][fix] fix invalid swagger feature

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
Does not work due to https://github.com/syndesisio/syndesis/issues/5573
//test: `@logout-test`
> [ui][fix] fix logout feature

- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
> [ui][fix] fix webhook feature

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/DataMapper.java
Added support for button dropdowns (only in fillBy method) & Added scroll back to plus sign in data mapper
//skip-ci
> Dropdowns and DM multiple mappings fix

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/detail/ApiClientConnectorDetail.java
- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/wizard/steps/SpecifySecurity.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
> [ui][fix] fix api client connectors crud feature

- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
//skip-ci
@mcada solves one problem, but is blocked by https://github.com/syndesisio/syndesis/issues/5647
> [REST] Fix datamapper id containing invalid characters

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
- ui-tests/src/test/resources/features/other/integration-activity.feature
update activity step test according to fix #4181 and skip error test due to #4192
//test: `@activity-test`
> [ui] - update activity step test according to fix #4181 

- rest-tests/src/test/java/io/syndesis/qe/RestTestHooks.java
- rest-tests/src/test/resources/features/integration-http-producer.feature
- rest-tests/src/test/resources/features/upgrade-prod.feature
//test: `@integration-http-sql-split`
> Rest tests update

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- utilities/src/main/java/io/syndesis/qe/utils/SampleDbConnectionManager.java
> [FUSEQE-4719] Use htpasswd login for OCP4

- ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
- ui-tests/src/test/resources/features/integrations/integration-import-export.feature
//test: `@validate-connection-credentials`
> [ui][fix] fill connection credentials in lower case by data-testid

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
> [ui][update] update logout test to use test-id selector

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/connections/detail/DetailSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/settings/SettingsSteps.java
- ui-tests/src/test/resources/features/integrations/twitter-to-db.feature
- ui-tests/src/test/resources/features/other/settings-oauth.feature
//test: `@settings-oauth-test`
> [ui][update] update oauth steps

- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/EnvironmentsPublicApiSteps.java
- rest-tests/src/test/java/io/syndesis/qe/rest/tests/publicapi/IntegrationsPublicApiSteps.java
- rest-tests/src/test/resources/features/publicapi/environments.feature
- rest-tests/src/test/resources/features/publicapi/integrations.feature
- utilities/src/main/java/io/syndesis/qe/endpoints/publicendpoint/EnvironmentsPublicEndpoint.java
* Test for a new endpoint for creating unassigned tag was added
* Update test, now the unassigned tag is not removed from the syndesis
* Add test for usage of tags
//test: `@publicapi`
> [rest] - Test for new endpoint was added

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
- ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
//skip-ci
the tests are blocked by 
https://github.com/syndesisio/syndesis/issues/5669
https://github.com/syndesisio/syndesis/issues/5892
https://github.com/syndesisio/syndesis/issues/5900
But they are all fixed - they just should fail on current syndesis version (1.7.4)
> [ui][fix] fix amq-to-rest and api-client-connector features

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/other/login-logout.feature
> [ui][fix] update logout tests to use new oauth flow

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/connections/connections.feature
> [ui][fix] fix connection validation test

- rest-tests/src/test/resources/features/integration-box.feature
- utilities/src/main/java/io/syndesis/qe/bdd/datamapper/AtlasMapperGenerator.java
- utilities/src/main/java/io/syndesis/qe/bdd/validation/BoxValidationSteps.java
//test: `@integration-box-amq`
> [FUSEQE-4760] Edit box test for current behavior

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/BasicFilter.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/steps/getridof/AbstractStep.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Metrics.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseStepSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
- ui-tests/src/test/resources/features/other/integration-activity.feature
- ui-tests/src/test/resources/features/other/integration-metrics.feature
_**[ui][fix] activity feature migration**_
* activity feature was migrated
* basic filter was migrated
* advanced filter was migrated
* activity view was migrated
_**[ui][fix] metrics feature migration**_
* metrics feature was migrated
* metrics view was migrated
* fixed work with a time in the activity test
//skip-ci
> [ui][fix] activity and metrics feature migration

- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/resources/features/connections/oauth.feature
> [ui] fixed oauth tests

- ui-tests/src/test/java/io/syndesis/qe/pages/SupportPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/AboutPageSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/SupportPageSteps.java
- ui-tests/src/test/resources/features/other/support-page.feature
//test: `@support-page-version-check`
The test should fail because build id is empty: https://github.com/syndesisio/syndesis/issues/5960
> [ui][fix] update support page tests

- ui-tests/src/test/resources/features/integrations/slack.feature
> fix slack tests

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/google/EventForm.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/editor/add/connection/actions/google/GetSpecificEvent.java
- ui-tests/src/test/java/io/syndesis/qe/pages/settings/SettingsPage.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/datamapper/DataMapperSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/GoogleCalendarSteps.java
- ui-tests/src/test/resources/features/integrations/google-calendar.feature
//test: `@google-calendar`
Contains a workaround for oauth creation issues.
> [ui][react] Fix google calendar tests

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/DetailsSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- ui-tests/src/test/resources/features/customizations/connectors/webhook.feature
//test: `@gh-5575`
Reproducer for https://github.com/syndesisio/syndesis/issues/5575
> [UI] - Reproducer for showing WebHook URL in UI

- ui-tests/src/test/java/io/syndesis/qe/steps/other/GMailSteps.java
- ui-tests/src/test/resources/features/integrations/email.feature
Email teste migration and email folders test.
//test: `@email`
> Email migration

- ui-tests/src/test/resources/features/connections/oauth.feature
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/salesforce-to-database.feature
- ui-tests/src/test/resources/features/integrations/template.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
> [ui][fix] update connectors creation to use OAuth

- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/api-client-connector-CRUD.feature
//dotest: `@create-delete-api-connector`
> [ui][fix] fix api client connector delete scenario

- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/data-buckets.feature
- ui-tests/src/test/resources/features/integrations/sql-connector.feature
- ui-tests/src/test/resources/features/integrations/twitter-to-salesforce.feature
> [ui][fix] add next button click where required

- ui-tests/src/test/java/io/syndesis/qe/steps/apps/todo/TodoSteps.java
- ui-tests/src/test/resources/features/integrations/amq-to-rest.feature
//test: `@integrations-amq-to-rest-xml-message`
> [ui][fix] fix amq-to-rest host property

- ui-tests/src/test/resources/features/integrations/db-to-db-with-extension.feature
//test: `@integrations-db-to-db-with-extension`
> [ui] Fix db-to-db-with-extension

- README.md
> updated information about running syndesis tests with chrome

- ui-tests/src/test/java/io/syndesis/qe/steps/connections/wizard/phases/ConfigureConnectionSteps.java
//test: `@validate-connection-credentials`
> [ui][fix] fix smoke tests

- ui-tests/src/test/java/io/syndesis/qe/hooks/CommonHooks.java
- utilities/src/main/java/io/syndesis/qe/templates/PublicOauthProxyTemplate.java
- utilities/src/main/java/io/syndesis/qe/utils/PublicApiUtils.java
//test: `@publicapi and @rest`
> [REST]Fix namespace in deleting cluster role bindings method

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/Form.java
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/add/ChooseConnectionSteps.java
- ui-tests/src/test/resources/features/integrations/gmail.feature
This also removes unnecessary wait time before button press and semi-unnecessary wait time after button press.
//test: `@integrations-gmail`
> [UI] fix gmail integration tests with new oauth connection creation

- pom.xml
- ui-tests/src/test/java/io/syndesis/qe/pages/connections/wizard/phases/NameConnection.java
- ui-tests/src/test/resources/features/integrations/twitter-direct-messages.feature
- utilities/src/main/java/io/syndesis/qe/bdd/validation/TwValidationSteps.java
These are new tests which test new feature - twitter direct messages
//test: `@integrations-twitter-direct-messages`
> [FUSEQE-4509] implementation of twitter DM testing

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Activity.java
> [UI] fix date selector in Activity tab

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@oauth-validate-connectors`
> [ui][fix] maximalize firefox on login and OAuth

- ui-tests/src/test/java/io/syndesis/qe/pages/ModalDialogPage.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationFlowView.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/editor/EditorSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/ConditionalFlowSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/other/InvokeHttpRequest.java
- ui-tests/src/test/resources/features/integrations/conditional-flow.feature
//test: `@integrations-conditional-flows`
> [ui][new] Conditional flow feature

- ui-tests/src/test/resources/features/integrations/telegram.feature
This is a manual test, so only smoke testing is required here.
Also I put my chat id into the tests for now.
> [FUSEQE-4322] telegram feature migration to react ui

- ui-tests/src/test/java/io/syndesis/qe/fragments/common/form/ApiSpecificationForm.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/importt/ImportIntegration.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApiClientConnectorsSteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/extensions/ExtensionSteps.java
- ui-tests/src/test/java/io/syndesis/qe/utils/UploadFile.java
//test: `@create-api-connector-from-file-test or @extension-CRUD-import-new or @import-edit-integration`
> [ui][fix] Workaround firefox file upload

- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/ActivitySteps.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/summary/MetricsSteps.java
//test: `@metrics and @activity-test`
> [UI] update metrics and activity tests according to fixed issues

- ui-tests/src/test/resources/features/integrations/api-client-connector.feature
- ui-tests/src/test/resources/features/integrations/webhook-api-connector.feature
//test: `@integrations-webhook-api-connector or @integrations-api-connector`
> [ui][fix] correctly fill todo host URL

- ui-tests/src/test/java/io/syndesis/qe/pages/customizations/connectors/ApiClientConnectors.java
- ui-tests/src/test/java/io/syndesis/qe/steps/customizations/connectors/ApicurioSteps.java
- ui-tests/src/test/resources/features/customizations/connectors/apicurio.feature
> Apicurito fixes rebase

- ui-tests/src/test/java/io/syndesis/qe/steps/CommonSteps.java
//test: `@create-delete-api-connector`
> [ui][update] update connection creation

- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/fragments/IntegrationsList.java
- ui-tests/src/test/java/io/syndesis/qe/pages/integrations/summary/Details.java
- ui-tests/src/test/java/io/syndesis/qe/steps/integrations/IntegrationSteps.java
- ui-tests/src/test/resources/features/integrations/integration-status.feature
//test: `@integrations-check-starting-status`
> integration status feature migration
